// Copyright 2026 The FinFocus Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: finfocus/v1/allocation.proto

package pbc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PricedResource is one priceable resource from GetStatsResponse.priceable
// after the host priced it.
type PricedResource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource as the usage source reported it. Nodes carry
	// tags.kind="node" and an id equal to the node's "node" subject value; a
	// control plane carries tags.kind="cluster". Entries are unique by
	// (tags.kind, id).
	Resource *ResourceDescriptor `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	// Cost for the normalized period, non-negative and finite. MUST be 0 when
	// priced is false.
	Cost float64 `protobuf:"fixed64,2,opt,name=cost,proto3" json:"cost,omitempty"`
	// ISO 4217 code. Across entries with priced=true there is one resolved
	// currency: the single distinct non-empty value, or "USD" when all are
	// empty. An empty value takes the resolved currency. Ignored when priced is
	// false. The "USD" fallback applies only within this contract.
	Currency string `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	// True when pricing succeeded. False entries count 0 toward conservation.
	Priced bool `protobuf:"varint,4,opt,name=priced,proto3" json:"priced,omitempty"`
	// Human-readable note, such as why pricing failed.
	Note          string `protobuf:"bytes,5,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PricedResource) Reset() {
	*x = PricedResource{}
	mi := &file_finfocus_v1_allocation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PricedResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PricedResource) ProtoMessage() {}

func (x *PricedResource) ProtoReflect() protoreflect.Message {
	mi := &file_finfocus_v1_allocation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PricedResource.ProtoReflect.Descriptor instead.
func (*PricedResource) Descriptor() ([]byte, []int) {
	return file_finfocus_v1_allocation_proto_rawDescGZIP(), []int{0}
}

func (x *PricedResource) GetResource() *ResourceDescriptor {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *PricedResource) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *PricedResource) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PricedResource) GetPriced() bool {
	if x != nil {
		return x.Priced
	}
	return false
}

func (x *PricedResource) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

// AllocateRequest carries usage, priced resources, and the allocation policy.
type AllocateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Usage rows as returned by UsageSourceService.GetStats.
	Usage []*UsageRow `protobuf:"bytes,1,rep,name=usage,proto3" json:"usage,omitempty"`
	// Priced resources; see PricedResource for the uniqueness and currency
	// rules.
	Priced []*PricedResource `protobuf:"bytes,2,rep,name=priced,proto3" json:"priced,omitempty"`
	// Allocator-owned JSON policy, opaque to the host. Every allocator's schema
	// has a top-level integer "version". Empty and "{}" both mean the
	// allocator's defaults and yield identical effective policy and digest.
	// Accepted overrides merge onto the defaults.
	PolicyJson []byte `protobuf:"bytes,3,opt,name=policy_json,json=policyJson,proto3" json:"policy_json,omitempty"`
	// Mode the usage was collected in. STATS_MODE_UNSPECIFIED is allowed:
	// allocation uses ratios of usage to capacity, so the result does not
	// depend on the mode.
	Mode StatsMode `protobuf:"varint,4,opt,name=mode,proto3,enum=finfocus.v1.StatsMode" json:"mode,omitempty"`
	// Start of the period the priced costs cover, with the same rules as
	// GetStatsRequest.start: set start and end together, or leave both unset for
	// a run-rate allocation. Setting exactly one is INVALID_ARGUMENT. The period
	// labels the result and never changes an allocated cost.
	Start *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start,proto3" json:"start,omitempty"`
	// End of the period. Must not be before start.
	End *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end,proto3" json:"end,omitempty"`
	// Workload selector the host used for usage, with the same meaning as
	// GetStatsRequest.selector. A non-empty selector is a partial selection:
	// node capacity still covers every workload, so idle and cluster rows
	// include capacity used by unselected workloads. Every invariant still
	// holds. Allocators SHOULD add a warning. Hosts SHOULD omit or label idle
	// and cluster rows for a partial selection.
	Selector      map[string]string `protobuf:"bytes,7,rep,name=selector,proto3" json:"selector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateRequest) Reset() {
	*x = AllocateRequest{}
	mi := &file_finfocus_v1_allocation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateRequest) ProtoMessage() {}

func (x *AllocateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finfocus_v1_allocation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateRequest.ProtoReflect.Descriptor instead.
func (*AllocateRequest) Descriptor() ([]byte, []int) {
	return file_finfocus_v1_allocation_proto_rawDescGZIP(), []int{1}
}

func (x *AllocateRequest) GetUsage() []*UsageRow {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *AllocateRequest) GetPriced() []*PricedResource {
	if x != nil {
		return x.Priced
	}
	return nil
}

func (x *AllocateRequest) GetPolicyJson() []byte {
	if x != nil {
		return x.PolicyJson
	}
	return nil
}

func (x *AllocateRequest) GetMode() StatsMode {
	if x != nil {
		return x.Mode
	}
	return StatsMode_STATS_MODE_UNSPECIFIED
}

func (x *AllocateRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *AllocateRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *AllocateRequest) GetSelector() map[string]string {
	if x != nil {
		return x.Selector
	}
	return nil
}

// AllocateResponse carries allocation rows and the policy actually applied.
// A request with no usage and no priced resources succeeds with no rows but
// with effective_policy_json and policy_digest, so hosts can display policy.
type AllocateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Allocation rows; see AllocatorService for the invariants.
	Rows []*AllocationRow `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	// The effective policy (defaults with overrides applied) in the
	// allocator's canonical JSON form. Never empty.
	EffectivePolicyJson []byte `protobuf:"bytes,2,opt,name=effective_policy_json,json=effectivePolicyJson,proto3" json:"effective_policy_json,omitempty"`
	// Lowercase hex SHA-256 of effective_policy_json. Stable: the same
	// effective policy always yields the same digest from the same allocator.
	// Not comparable across different allocators.
	PolicyDigest string `protobuf:"bytes,3,opt,name=policy_digest,json=policyDigest,proto3" json:"policy_digest,omitempty"`
	// Human-readable, non-fatal warnings.
	Warnings []string `protobuf:"bytes,4,rep,name=warnings,proto3" json:"warnings,omitempty"`
	// Echo of AllocateRequest.start. Allocators MUST echo the request's period
	// exactly. Hosts accept a response without a period (from allocators built
	// before these fields) and reject one that differs from the request.
	Start *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start,proto3" json:"start,omitempty"`
	// Echo of AllocateRequest.end.
	End           *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateResponse) Reset() {
	*x = AllocateResponse{}
	mi := &file_finfocus_v1_allocation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateResponse) ProtoMessage() {}

func (x *AllocateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finfocus_v1_allocation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateResponse.ProtoReflect.Descriptor instead.
func (*AllocateResponse) Descriptor() ([]byte, []int) {
	return file_finfocus_v1_allocation_proto_rawDescGZIP(), []int{2}
}

func (x *AllocateResponse) GetRows() []*AllocationRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *AllocateResponse) GetEffectivePolicyJson() []byte {
	if x != nil {
		return x.EffectivePolicyJson
	}
	return nil
}

func (x *AllocateResponse) GetPolicyDigest() string {
	if x != nil {
		return x.PolicyDigest
	}
	return ""
}

func (x *AllocateResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *AllocateResponse) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *AllocateResponse) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

// AllocationRow is one unit of allocated cost.
type AllocationRow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifies what the cost belongs to, using the UsageRow subject keys. The
	// required "kind" is "workload", "__idle__" (unclaimed capacity of one node;
	// requires the "node" key), or "__cluster__" (shared infrastructure such as
	// the control plane, or a priced resource that is not a node).
	Subject map[string]string `protobuf:"bytes,1,rep,name=subject,proto3" json:"subject,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// CPU portion of the cost; non-negative.
	CpuCost float64 `protobuf:"fixed64,2,opt,name=cpu_cost,json=cpuCost,proto3" json:"cpu_cost,omitempty"`
	// Memory portion of the cost; non-negative.
	MemCost float64 `protobuf:"fixed64,3,opt,name=mem_cost,json=memCost,proto3" json:"mem_cost,omitempty"`
	// Total cost; non-negative. Equals cpu_cost + mem_cost except on
	// "__cluster__" rows, which may carry all cost here with zero portions.
	TotalCost float64 `protobuf:"fixed64,4,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	// The resolved currency; never empty.
	Currency string `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	// Human-readable note, such as why a workload's cost is zero.
	Note string `protobuf:"bytes,6,opt,name=note,proto3" json:"note,omitempty"`
	// Optional FOCUS 1.3 AllocatedMethodId: identifies the method the allocator
	// used to produce this row. An opaque, allocator-defined string. A non-empty
	// value requires allocated_resource_id to be non-empty, as in FOCUS 1.3
	// (hosts and ValidateAllocateResponse reject the row otherwise).
	AllocatedMethodId string `protobuf:"bytes,7,opt,name=allocated_method_id,json=allocatedMethodId,proto3" json:"allocated_method_id,omitempty"`
	// Optional FOCUS 1.3 AllocatedMethodDetails: free-form description of how
	// the cost was split. Allowed without allocated_method_id. FOCUS 1.4 defines
	// this column as a JSON object; the contract does not enforce a format.
	AllocatedMethodDetails string `protobuf:"bytes,8,opt,name=allocated_method_details,json=allocatedMethodDetails,proto3" json:"allocated_method_details,omitempty"`
	// Optional FOCUS 1.3 AllocatedResourceId: the priced resource this row's
	// cost came from, by convention the resource.id of the PricedResource (a
	// node id for workload and idle rows). Opaque; not cross-checked against
	// the request.
	AllocatedResourceId string `protobuf:"bytes,9,opt,name=allocated_resource_id,json=allocatedResourceId,proto3" json:"allocated_resource_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AllocationRow) Reset() {
	*x = AllocationRow{}
	mi := &file_finfocus_v1_allocation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocationRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocationRow) ProtoMessage() {}

func (x *AllocationRow) ProtoReflect() protoreflect.Message {
	mi := &file_finfocus_v1_allocation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocationRow.ProtoReflect.Descriptor instead.
func (*AllocationRow) Descriptor() ([]byte, []int) {
	return file_finfocus_v1_allocation_proto_rawDescGZIP(), []int{3}
}

func (x *AllocationRow) GetSubject() map[string]string {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *AllocationRow) GetCpuCost() float64 {
	if x != nil {
		return x.CpuCost
	}
	return 0
}

func (x *AllocationRow) GetMemCost() float64 {
	if x != nil {
		return x.MemCost
	}
	return 0
}

func (x *AllocationRow) GetTotalCost() float64 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

func (x *AllocationRow) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *AllocationRow) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *AllocationRow) GetAllocatedMethodId() string {
	if x != nil {
		return x.AllocatedMethodId
	}
	return ""
}

func (x *AllocationRow) GetAllocatedMethodDetails() string {
	if x != nil {
		return x.AllocatedMethodDetails
	}
	return ""
}

func (x *AllocationRow) GetAllocatedResourceId() string {
	if x != nil {
		return x.AllocatedResourceId
	}
	return ""
}

var File_finfocus_v1_allocation_proto protoreflect.FileDescriptor

const file_finfocus_v1_allocation_proto_rawDesc = "" +
	"\n" +
	"\x1cfinfocus/v1/allocation.proto\x12\vfinfocus.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cfinfocus/v1/costsource.proto\x1a\x17finfocus/v1/usage.proto\"\xa9\x01\n" +
	"\x0ePricedResource\x12;\n" +
	"\bresource\x18\x01 \x01(\v2\x1f.finfocus.v1.ResourceDescriptorR\bresource\x12\x12\n" +
	"\x04cost\x18\x02 \x01(\x01R\x04cost\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06priced\x18\x04 \x01(\bR\x06priced\x12\x12\n" +
	"\x04note\x18\x05 \x01(\tR\x04note\"\xa5\x03\n" +
	"\x0fAllocateRequest\x12+\n" +
	"\x05usage\x18\x01 \x03(\v2\x15.finfocus.v1.UsageRowR\x05usage\x123\n" +
	"\x06priced\x18\x02 \x03(\v2\x1b.finfocus.v1.PricedResourceR\x06priced\x12\x1f\n" +
	"\vpolicy_json\x18\x03 \x01(\fR\n" +
	"policyJson\x12*\n" +
	"\x04mode\x18\x04 \x01(\x0e2\x16.finfocus.v1.StatsModeR\x04mode\x120\n" +
	"\x05start\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\x12F\n" +
	"\bselector\x18\a \x03(\v2*.finfocus.v1.AllocateRequest.SelectorEntryR\bselector\x1a;\n" +
	"\rSelectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x97\x02\n" +
	"\x10AllocateResponse\x12.\n" +
	"\x04rows\x18\x01 \x03(\v2\x1a.finfocus.v1.AllocationRowR\x04rows\x122\n" +
	"\x15effective_policy_json\x18\x02 \x01(\fR\x13effectivePolicyJson\x12#\n" +
	"\rpolicy_digest\x18\x03 \x01(\tR\fpolicyDigest\x12\x1a\n" +
	"\bwarnings\x18\x04 \x03(\tR\bwarnings\x120\n" +
	"\x05start\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\"\xb1\x03\n" +
	"\rAllocationRow\x12A\n" +
	"\asubject\x18\x01 \x03(\v2'.finfocus.v1.AllocationRow.SubjectEntryR\asubject\x12\x19\n" +
	"\bcpu_cost\x18\x02 \x01(\x01R\acpuCost\x12\x19\n" +
	"\bmem_cost\x18\x03 \x01(\x01R\amemCost\x12\x1d\n" +
	"\n" +
	"total_cost\x18\x04 \x01(\x01R\ttotalCost\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x12\n" +
	"\x04note\x18\x06 \x01(\tR\x04note\x12.\n" +
	"\x13allocated_method_id\x18\a \x01(\tR\x11allocatedMethodId\x128\n" +
	"\x18allocated_method_details\x18\b \x01(\tR\x16allocatedMethodDetails\x122\n" +
	"\x15allocated_resource_id\x18\t \x01(\tR\x13allocatedResourceId\x1a:\n" +
	"\fSubjectEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012[\n" +
	"\x10AllocatorService\x12G\n" +
	"\bAllocate\x12\x1c.finfocus.v1.AllocateRequest\x1a\x1d.finfocus.v1.AllocateResponseB\xad\x01\n" +
	"\x0fcom.finfocus.v1B\x0fAllocationProtoP\x01Z<github.com/rshade/finfocus-spec/sdk/go/proto/finfocus/v1;pbc\xa2\x02\x03FXX\xaa\x02\vFinfocus.V1\xca\x02\vFinfocus\\V1\xe2\x02\x17Finfocus\\V1\\GPBMetadata\xea\x02\fFinfocus::V1b\x06proto3"

var (
	file_finfocus_v1_allocation_proto_rawDescOnce sync.Once
	file_finfocus_v1_allocation_proto_rawDescData []byte
)

func file_finfocus_v1_allocation_proto_rawDescGZIP() []byte {
	file_finfocus_v1_allocation_proto_rawDescOnce.Do(func() {
		file_finfocus_v1_allocation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_finfocus_v1_allocation_proto_rawDesc), len(file_finfocus_v1_allocation_proto_rawDesc)))
	})
	return file_finfocus_v1_allocation_proto_rawDescData
}

var file_finfocus_v1_allocation_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_finfocus_v1_allocation_proto_goTypes = []any{
	(*PricedResource)(nil),        // 0: finfocus.v1.PricedResource
	(*AllocateRequest)(nil),       // 1: finfocus.v1.AllocateRequest
	(*AllocateResponse)(nil),      // 2: finfocus.v1.AllocateResponse
	(*AllocationRow)(nil),         // 3: finfocus.v1.AllocationRow
	nil,                           // 4: finfocus.v1.AllocateRequest.SelectorEntry
	nil,                           // 5: finfocus.v1.AllocationRow.SubjectEntry
	(*ResourceDescriptor)(nil),    // 6: finfocus.v1.ResourceDescriptor
	(*UsageRow)(nil),              // 7: finfocus.v1.UsageRow
	(StatsMode)(0),                // 8: finfocus.v1.StatsMode
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_finfocus_v1_allocation_proto_depIdxs = []int32{
	6,  // 0: finfocus.v1.PricedResource.resource:type_name -> finfocus.v1.ResourceDescriptor
	7,  // 1: finfocus.v1.AllocateRequest.usage:type_name -> finfocus.v1.UsageRow
	0,  // 2: finfocus.v1.AllocateRequest.priced:type_name -> finfocus.v1.PricedResource
	8,  // 3: finfocus.v1.AllocateRequest.mode:type_name -> finfocus.v1.StatsMode
	9,  // 4: finfocus.v1.AllocateRequest.start:type_name -> google.protobuf.Timestamp
	9,  // 5: finfocus.v1.AllocateRequest.end:type_name -> google.protobuf.Timestamp
	4,  // 6: finfocus.v1.AllocateRequest.selector:type_name -> finfocus.v1.AllocateRequest.SelectorEntry
	3,  // 7: finfocus.v1.AllocateResponse.rows:type_name -> finfocus.v1.AllocationRow
	9,  // 8: finfocus.v1.AllocateResponse.start:type_name -> google.protobuf.Timestamp
	9,  // 9: finfocus.v1.AllocateResponse.end:type_name -> google.protobuf.Timestamp
	5,  // 10: finfocus.v1.AllocationRow.subject:type_name -> finfocus.v1.AllocationRow.SubjectEntry
	1,  // 11: finfocus.v1.AllocatorService.Allocate:input_type -> finfocus.v1.AllocateRequest
	2,  // 12: finfocus.v1.AllocatorService.Allocate:output_type -> finfocus.v1.AllocateResponse
	12, // [12:13] is the sub-list for method output_type
	11, // [11:12] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_finfocus_v1_allocation_proto_init() }
func file_finfocus_v1_allocation_proto_init() {
	if File_finfocus_v1_allocation_proto != nil {
		return
	}
	file_finfocus_v1_costsource_proto_init()
	file_finfocus_v1_usage_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_finfocus_v1_allocation_proto_rawDesc), len(file_finfocus_v1_allocation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_finfocus_v1_allocation_proto_goTypes,
		DependencyIndexes: file_finfocus_v1_allocation_proto_depIdxs,
		MessageInfos:      file_finfocus_v1_allocation_proto_msgTypes,
	}.Build()
	File_finfocus_v1_allocation_proto = out.File
	file_finfocus_v1_allocation_proto_goTypes = nil
	file_finfocus_v1_allocation_proto_depIdxs = nil
}
