// Copyright 2026 The FinFocus Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: finfocus/v1/allocation.proto

package pbc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AllocatorService_Allocate_FullMethodName = "/finfocus.v1.AllocatorService/Allocate"
)

// AllocatorServiceClient is the client API for AllocatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AllocatorService is implemented by allocator plugins, which divide priced
// infrastructure (nodes, control plane) across the workloads that use it.
// Hosts gather usage through UsageSourceService, price the priceable resources
// through CostSourceService plugins, and call Allocate. Hosts carry no
// allocation semantics; the math belongs to the allocator.
//
// Invariants every response MUST satisfy (hosts verify them and reject
// violations; the Go SDK exposes the checks as pluginsdk.CheckConservation and
// pluginsdk.ValidateAllocateResponse):
//   - Conservation: the sum of rows.total_cost equals the sum of priced.cost
//     over entries with priced=true, within a relative tolerance of 1e-6 with
//     an absolute floor of 1e-9, so zero totals compare equal.
//   - Every row has total_cost = cpu_cost + mem_cost within the same
//     tolerance, except rows with subject kind "__cluster__".
//   - No row carries a negative cpu_cost, mem_cost, or total_cost.
//   - Every successfully priced node (priced=true, resource.tags.kind="node")
//     has exactly one "__idle__" row whose "node" subject equals the node's
//     resource.id, even when its idle cost is zero.
//   - Every row carries the resolved currency (see AllocateRequest.priced).
//   - A row with a non-empty allocated_method_id has a non-empty
//     allocated_resource_id.
//
// Error semantics:
//   - INVALID_ARGUMENT: the request is inconsistent (an entry with priced=false
//     and a nonzero cost, a negative cost, more than one distinct non-empty
//     currency among priced=true entries, or two entries with the same
//     resource.tags.kind and resource.id), or policy_json is malformed, has
//     trailing data, has an unknown field (the message names its JSON path,
//     for example "node_split.cpu"), or has an unknown or unsupported version.
//     An allocator never falls back to defaults on a bad policy.
type AllocatorServiceClient interface {
	// Allocate divides the successfully priced resources across the workloads
	// in usage, reporting unclaimed capacity as idle rows and shared
	// infrastructure as cluster rows.
	Allocate(ctx context.Context, in *AllocateRequest, opts ...grpc.CallOption) (*AllocateResponse, error)
}

type allocatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAllocatorServiceClient(cc grpc.ClientConnInterface) AllocatorServiceClient {
	return &allocatorServiceClient{cc}
}

func (c *allocatorServiceClient) Allocate(ctx context.Context, in *AllocateRequest, opts ...grpc.CallOption) (*AllocateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllocateResponse)
	err := c.cc.Invoke(ctx, AllocatorService_Allocate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AllocatorServiceServer is the server API for AllocatorService service.
// All implementations must embed UnimplementedAllocatorServiceServer
// for forward compatibility.
//
// AllocatorService is implemented by allocator plugins, which divide priced
// infrastructure (nodes, control plane) across the workloads that use it.
// Hosts gather usage through UsageSourceService, price the priceable resources
// through CostSourceService plugins, and call Allocate. Hosts carry no
// allocation semantics; the math belongs to the allocator.
//
// Invariants every response MUST satisfy (hosts verify them and reject
// violations; the Go SDK exposes the checks as pluginsdk.CheckConservation and
// pluginsdk.ValidateAllocateResponse):
//   - Conservation: the sum of rows.total_cost equals the sum of priced.cost
//     over entries with priced=true, within a relative tolerance of 1e-6 with
//     an absolute floor of 1e-9, so zero totals compare equal.
//   - Every row has total_cost = cpu_cost + mem_cost within the same
//     tolerance, except rows with subject kind "__cluster__".
//   - No row carries a negative cpu_cost, mem_cost, or total_cost.
//   - Every successfully priced node (priced=true, resource.tags.kind="node")
//     has exactly one "__idle__" row whose "node" subject equals the node's
//     resource.id, even when its idle cost is zero.
//   - Every row carries the resolved currency (see AllocateRequest.priced).
//   - A row with a non-empty allocated_method_id has a non-empty
//     allocated_resource_id.
//
// Error semantics:
//   - INVALID_ARGUMENT: the request is inconsistent (an entry with priced=false
//     and a nonzero cost, a negative cost, more than one distinct non-empty
//     currency among priced=true entries, or two entries with the same
//     resource.tags.kind and resource.id), or policy_json is malformed, has
//     trailing data, has an unknown field (the message names its JSON path,
//     for example "node_split.cpu"), or has an unknown or unsupported version.
//     An allocator never falls back to defaults on a bad policy.
type AllocatorServiceServer interface {
	// Allocate divides the successfully priced resources across the workloads
	// in usage, reporting unclaimed capacity as idle rows and shared
	// infrastructure as cluster rows.
	Allocate(context.Context, *AllocateRequest) (*AllocateResponse, error)
	mustEmbedUnimplementedAllocatorServiceServer()
}

// UnimplementedAllocatorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAllocatorServiceServer struct{}

func (UnimplementedAllocatorServiceServer) Allocate(context.Context, *AllocateRequest) (*AllocateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Allocate not implemented")
}
func (UnimplementedAllocatorServiceServer) mustEmbedUnimplementedAllocatorServiceServer() {}
func (UnimplementedAllocatorServiceServer) testEmbeddedByValue()                          {}

// UnsafeAllocatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AllocatorServiceServer will
// result in compilation errors.
type UnsafeAllocatorServiceServer interface {
	mustEmbedUnimplementedAllocatorServiceServer()
}

func RegisterAllocatorServiceServer(s grpc.ServiceRegistrar, srv AllocatorServiceServer) {
	// If the following call panics, it indicates UnimplementedAllocatorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AllocatorService_ServiceDesc, srv)
}

func _AllocatorService_Allocate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AllocatorServiceServer).Allocate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AllocatorService_Allocate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AllocatorServiceServer).Allocate(ctx, req.(*AllocateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AllocatorService_ServiceDesc is the grpc.ServiceDesc for AllocatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AllocatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "finfocus.v1.AllocatorService",
	HandlerType: (*AllocatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Allocate",
			Handler:    _AllocatorService_Allocate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "finfocus/v1/allocation.proto",
}
