// Copyright 2026 The FinFocus Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: finfocus/v1/scoring.proto

package pbc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RecommendationScorerService_ScoreRecommendations_FullMethodName = "/finfocus.v1.RecommendationScorerService/ScoreRecommendations"
)

// RecommendationScorerServiceClient is the client API for RecommendationScorerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RecommendationScorerService is implemented by scorer plugins, which rate
// recommendations that other plugins produced. A scorer adds judgement the
// producing plugins do not carry: how risky acting is, whether the resource
// is probably in that state on purpose, whether the recommendation is worth an
// engineer's time, whether the evidence is thin, and which recommendations
// duplicate each other. A scorer never creates, changes, or applies a
// recommendation, and a score is never approval to act.
//
// Scores are ranking signals, not calibrated probabilities. Hosts MUST NOT use
// a score as the only gate for an irreversible action, and MUST treat every
// free-text field of the request as untrusted input.
//
// Error semantics:
//   - INVALID_ARGUMENT: recommendations is empty, holds more entries than
//     max_batch_size, holds two entries with the same id, or names a signal the
//     scorer does not support in signals.
//   - UNIMPLEMENTED: the plugin does not implement scoring. Hosts check
//     PLUGIN_CAPABILITY_RECOMMENDATION_SCORING first and do not call it.
//   - UNAUTHENTICATED, PERMISSION_DENIED, RESOURCE_EXHAUSTED, UNAVAILABLE:
//     the scorer's backend refused or could not serve the whole call. A failure
//     that affects one recommendation is reported in its result instead.
type RecommendationScorerServiceClient interface {
	// ScoreRecommendations rates each recommendation in the request. Results are
	// index-aligned: results[i] answers recommendations[i]. One failing entry
	// never fails the batch.
	ScoreRecommendations(ctx context.Context, in *ScoreRecommendationsRequest, opts ...grpc.CallOption) (*ScoreRecommendationsResponse, error)
}

type recommendationScorerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRecommendationScorerServiceClient(cc grpc.ClientConnInterface) RecommendationScorerServiceClient {
	return &recommendationScorerServiceClient{cc}
}

func (c *recommendationScorerServiceClient) ScoreRecommendations(ctx context.Context, in *ScoreRecommendationsRequest, opts ...grpc.CallOption) (*ScoreRecommendationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScoreRecommendationsResponse)
	err := c.cc.Invoke(ctx, RecommendationScorerService_ScoreRecommendations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecommendationScorerServiceServer is the server API for RecommendationScorerService service.
// All implementations must embed UnimplementedRecommendationScorerServiceServer
// for forward compatibility.
//
// RecommendationScorerService is implemented by scorer plugins, which rate
// recommendations that other plugins produced. A scorer adds judgement the
// producing plugins do not carry: how risky acting is, whether the resource
// is probably in that state on purpose, whether the recommendation is worth an
// engineer's time, whether the evidence is thin, and which recommendations
// duplicate each other. A scorer never creates, changes, or applies a
// recommendation, and a score is never approval to act.
//
// Scores are ranking signals, not calibrated probabilities. Hosts MUST NOT use
// a score as the only gate for an irreversible action, and MUST treat every
// free-text field of the request as untrusted input.
//
// Error semantics:
//   - INVALID_ARGUMENT: recommendations is empty, holds more entries than
//     max_batch_size, holds two entries with the same id, or names a signal the
//     scorer does not support in signals.
//   - UNIMPLEMENTED: the plugin does not implement scoring. Hosts check
//     PLUGIN_CAPABILITY_RECOMMENDATION_SCORING first and do not call it.
//   - UNAUTHENTICATED, PERMISSION_DENIED, RESOURCE_EXHAUSTED, UNAVAILABLE:
//     the scorer's backend refused or could not serve the whole call. A failure
//     that affects one recommendation is reported in its result instead.
type RecommendationScorerServiceServer interface {
	// ScoreRecommendations rates each recommendation in the request. Results are
	// index-aligned: results[i] answers recommendations[i]. One failing entry
	// never fails the batch.
	ScoreRecommendations(context.Context, *ScoreRecommendationsRequest) (*ScoreRecommendationsResponse, error)
	mustEmbedUnimplementedRecommendationScorerServiceServer()
}

// UnimplementedRecommendationScorerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecommendationScorerServiceServer struct{}

func (UnimplementedRecommendationScorerServiceServer) ScoreRecommendations(context.Context, *ScoreRecommendationsRequest) (*ScoreRecommendationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScoreRecommendations not implemented")
}
func (UnimplementedRecommendationScorerServiceServer) mustEmbedUnimplementedRecommendationScorerServiceServer() {
}
func (UnimplementedRecommendationScorerServiceServer) testEmbeddedByValue() {}

// UnsafeRecommendationScorerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecommendationScorerServiceServer will
// result in compilation errors.
type UnsafeRecommendationScorerServiceServer interface {
	mustEmbedUnimplementedRecommendationScorerServiceServer()
}

func RegisterRecommendationScorerServiceServer(s grpc.ServiceRegistrar, srv RecommendationScorerServiceServer) {
	// If the following call panics, it indicates UnimplementedRecommendationScorerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecommendationScorerService_ServiceDesc, srv)
}

func _RecommendationScorerService_ScoreRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScoreRecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendationScorerServiceServer).ScoreRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommendationScorerService_ScoreRecommendations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendationScorerServiceServer).ScoreRecommendations(ctx, req.(*ScoreRecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RecommendationScorerService_ServiceDesc is the grpc.ServiceDesc for RecommendationScorerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecommendationScorerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "finfocus.v1.RecommendationScorerService",
	HandlerType: (*RecommendationScorerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScoreRecommendations",
			Handler:    _RecommendationScorerService_ScoreRecommendations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "finfocus/v1/scoring.proto",
}
