// Copyright 2026 The FinFocus Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: finfocus/v1/scoring.proto

package pbc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ScoreSignal names one kind of score a scorer can return.
type ScoreSignal int32

const (
	// SCORE_SIGNAL_UNSPECIFIED is invalid in a request.
	ScoreSignal_SCORE_SIGNAL_UNSPECIFIED ScoreSignal = 0
	// Risk that applying the recommendation hurts users, loses data, causes a
	// performance regression, or locks in a financial commitment that is hard to
	// undo. 0 is low risk, 1 is high risk.
	ScoreSignal_SCORE_SIGNAL_RISK ScoreSignal = 1
	// Likelihood that the resource is in the flagged state on purpose (standby,
	// seasonal, compliance retention, headroom), so the recommendation is wrong
	// for it. 0 is genuinely wasteful, 1 is probably intentional.
	ScoreSignal_SCORE_SIGNAL_FALSE_POSITIVE ScoreSignal = 2
	// Whether the recommendation is worth an engineer's time now, weighing
	// saving, risk and effort. 0 is not worth it, 1 is clearly worth it.
	ScoreSignal_SCORE_SIGNAL_WORTH_ACTING ScoreSignal = 3
	// Expected priority on a four-level scale, from 0 (ignore) to 3 (high).
	// Fractional values fall between levels.
	ScoreSignal_SCORE_SIGNAL_PRIORITY ScoreSignal = 4
	// Whether the record is too thin or contradictory to judge. 0 is enough
	// evidence, 1 is too little.
	ScoreSignal_SCORE_SIGNAL_INSUFFICIENT_EVIDENCE ScoreSignal = 5
	// Grouping of recommendations that describe the same change to the same
	// resource. Carried in RecommendationScores.duplicate_group_id.
	ScoreSignal_SCORE_SIGNAL_DUPLICATE_GROUP ScoreSignal = 6
)

// Enum value maps for ScoreSignal.
var (
	ScoreSignal_name = map[int32]string{
		0: "SCORE_SIGNAL_UNSPECIFIED",
		1: "SCORE_SIGNAL_RISK",
		2: "SCORE_SIGNAL_FALSE_POSITIVE",
		3: "SCORE_SIGNAL_WORTH_ACTING",
		4: "SCORE_SIGNAL_PRIORITY",
		5: "SCORE_SIGNAL_INSUFFICIENT_EVIDENCE",
		6: "SCORE_SIGNAL_DUPLICATE_GROUP",
	}
	ScoreSignal_value = map[string]int32{
		"SCORE_SIGNAL_UNSPECIFIED":           0,
		"SCORE_SIGNAL_RISK":                  1,
		"SCORE_SIGNAL_FALSE_POSITIVE":        2,
		"SCORE_SIGNAL_WORTH_ACTING":          3,
		"SCORE_SIGNAL_PRIORITY":              4,
		"SCORE_SIGNAL_INSUFFICIENT_EVIDENCE": 5,
		"SCORE_SIGNAL_DUPLICATE_GROUP":       6,
	}
)

func (x ScoreSignal) Enum() *ScoreSignal {
	p := new(ScoreSignal)
	*p = x
	return p
}

func (x ScoreSignal) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScoreSignal) Descriptor() protoreflect.EnumDescriptor {
	return file_finfocus_v1_scoring_proto_enumTypes[0].Descriptor()
}

func (ScoreSignal) Type() protoreflect.EnumType {
	return &file_finfocus_v1_scoring_proto_enumTypes[0]
}

func (x ScoreSignal) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScoreSignal.Descriptor instead.
func (ScoreSignal) EnumDescriptor() ([]byte, []int) {
	return file_finfocus_v1_scoring_proto_rawDescGZIP(), []int{0}
}

// ScoreCalibration says how a scorer's numeric signals may be read.
type ScoreCalibration int32

const (
	// SCORE_CALIBRATION_UNSPECIFIED means the scorer made no claim; hosts treat
	// it as SCORE_CALIBRATION_RANKING_ONLY.
	ScoreCalibration_SCORE_CALIBRATION_UNSPECIFIED ScoreCalibration = 0
	// Values order recommendations but are not probabilities. Compare them only
	// with each other and pick thresholds against labelled data.
	ScoreCalibration_SCORE_CALIBRATION_RANKING_ONLY ScoreCalibration = 1
	// Values are calibrated probabilities the scorer has checked against
	// outcomes.
	ScoreCalibration_SCORE_CALIBRATION_PROBABILITY ScoreCalibration = 2
)

// Enum value maps for ScoreCalibration.
var (
	ScoreCalibration_name = map[int32]string{
		0: "SCORE_CALIBRATION_UNSPECIFIED",
		1: "SCORE_CALIBRATION_RANKING_ONLY",
		2: "SCORE_CALIBRATION_PROBABILITY",
	}
	ScoreCalibration_value = map[string]int32{
		"SCORE_CALIBRATION_UNSPECIFIED":  0,
		"SCORE_CALIBRATION_RANKING_ONLY": 1,
		"SCORE_CALIBRATION_PROBABILITY":  2,
	}
)

func (x ScoreCalibration) Enum() *ScoreCalibration {
	p := new(ScoreCalibration)
	*p = x
	return p
}

func (x ScoreCalibration) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScoreCalibration) Descriptor() protoreflect.EnumDescriptor {
	return file_finfocus_v1_scoring_proto_enumTypes[1].Descriptor()
}

func (ScoreCalibration) Type() protoreflect.EnumType {
	return &file_finfocus_v1_scoring_proto_enumTypes[1]
}

func (x ScoreCalibration) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScoreCalibration.Descriptor instead.
func (ScoreCalibration) EnumDescriptor() ([]byte, []int) {
	return file_finfocus_v1_scoring_proto_rawDescGZIP(), []int{1}
}

// IdentifierMode controls how the host presents resource identifiers to a
// scorer that sends data off-host.
type IdentifierMode int32

const (
	// IDENTIFIER_MODE_UNSPECIFIED is treated as IDENTIFIER_MODE_PSEUDONYMIZED.
	IdentifierMode_IDENTIFIER_MODE_UNSPECIFIED IdentifierMode = 0
	// Raw cloud identifiers (resource id, name, ARN) are sent as they are.
	IdentifierMode_IDENTIFIER_MODE_RAW IdentifierMode = 1
	// resource.id and resource.name are replaced by opaque tokens that are
	// identical for the same value within one request and carry no meaning
	// outside it. Duplicate grouping keeps working. When the request carries a
	// session_id, the host uses one pseudonymization key for every batch of that
	// session, so a value has one token across those batches.
	IdentifierMode_IDENTIFIER_MODE_PSEUDONYMIZED IdentifierMode = 2
	// resource.id and resource.name are removed. Duplicate grouping becomes
	// unreliable; a scorer that cannot group returns no duplicate_group_id.
	IdentifierMode_IDENTIFIER_MODE_OMITTED IdentifierMode = 3
)

// Enum value maps for IdentifierMode.
var (
	IdentifierMode_name = map[int32]string{
		0: "IDENTIFIER_MODE_UNSPECIFIED",
		1: "IDENTIFIER_MODE_RAW",
		2: "IDENTIFIER_MODE_PSEUDONYMIZED",
		3: "IDENTIFIER_MODE_OMITTED",
	}
	IdentifierMode_value = map[string]int32{
		"IDENTIFIER_MODE_UNSPECIFIED":   0,
		"IDENTIFIER_MODE_RAW":           1,
		"IDENTIFIER_MODE_PSEUDONYMIZED": 2,
		"IDENTIFIER_MODE_OMITTED":       3,
	}
)

func (x IdentifierMode) Enum() *IdentifierMode {
	p := new(IdentifierMode)
	*p = x
	return p
}

func (x IdentifierMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IdentifierMode) Descriptor() protoreflect.EnumDescriptor {
	return file_finfocus_v1_scoring_proto_enumTypes[2].Descriptor()
}

func (IdentifierMode) Type() protoreflect.EnumType {
	return &file_finfocus_v1_scoring_proto_enumTypes[2]
}

func (x IdentifierMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IdentifierMode.Descriptor instead.
func (IdentifierMode) EnumDescriptor() ([]byte, []int) {
	return file_finfocus_v1_scoring_proto_rawDescGZIP(), []int{2}
}

// ScoreRecommendationsRequest carries recommendations to score.
type ScoreRecommendationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// recommendations are complete Recommendation messages as returned by
	// GetRecommendations, so the scorer sees action_detail, primary_reason,
	// secondary_reasons, tags, metadata, impact and utilization. The host does
	// not drop those fields on its own; an operator allowlist may remove them.
	// Between 1 and max_batch_size entries, each with a distinct id.
	Recommendations []*Recommendation `protobuf:"bytes,1,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	// signals limits the response to these signals. Empty means every signal the
	// scorer supports.
	Signals []ScoreSignal `protobuf:"varint,2,rep,packed,name=signals,proto3,enum=finfocus.v1.ScoreSignal" json:"signals,omitempty"`
	// identifier_mode is how the host has already treated resource identifiers
	// in recommendations. It informs the scorer; the host performs the
	// transformation. It covers resource.id and resource.name only: action_detail
	// members and free text (reasons, description, tags, metadata) can still hold
	// identifiers, and a scorer must not assume they were transformed.
	IdentifierMode IdentifierMode `protobuf:"varint,3,opt,name=identifier_mode,json=identifierMode,proto3,enum=finfocus.v1.IdentifierMode" json:"identifier_mode,omitempty"`
	// session_id names one host operation that spans several calls, for example
	// the batches of a set larger than max_batch_size. Empty means no session and
	// every rule is scoped to this request. When set it is 1 to 128 printable
	// ASCII characters (0x21 to 0x7E). The host sends the same value with every
	// batch of the operation, uses one pseudonymization key for all of them, and
	// never reuses the value for another operation or key. A scorer that honors
	// sessions derives duplicate_group_id from session_id and the duplicate key,
	// keeps no state between calls, and echoes the value in the response.
	// Recommendations the host leaves out of every batch are never grouped.
	SessionId     string `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreRecommendationsRequest) Reset() {
	*x = ScoreRecommendationsRequest{}
	mi := &file_finfocus_v1_scoring_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreRecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreRecommendationsRequest) ProtoMessage() {}

func (x *ScoreRecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finfocus_v1_scoring_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreRecommendationsRequest.ProtoReflect.Descriptor instead.
func (*ScoreRecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_finfocus_v1_scoring_proto_rawDescGZIP(), []int{0}
}

func (x *ScoreRecommendationsRequest) GetRecommendations() []*Recommendation {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

func (x *ScoreRecommendationsRequest) GetSignals() []ScoreSignal {
	if x != nil {
		return x.Signals
	}
	return nil
}

func (x *ScoreRecommendationsRequest) GetIdentifierMode() IdentifierMode {
	if x != nil {
		return x.IdentifierMode
	}
	return IdentifierMode_IDENTIFIER_MODE_UNSPECIFIED
}

func (x *ScoreRecommendationsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// ScoreRecommendationsResponse carries the scores.
type ScoreRecommendationsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// results has one entry per request entry, in request order.
	Results []*RecommendationScoreResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	// max_batch_size is the largest number of recommendations the scorer accepts
	// in one call. Hosts split larger sets.
	MaxBatchSize int32 `protobuf:"varint,2,opt,name=max_batch_size,json=maxBatchSize,proto3" json:"max_batch_size,omitempty"`
	// scorer identifies who produced the scores.
	Scorer *ScorerInfo `protobuf:"bytes,3,opt,name=scorer,proto3" json:"scorer,omitempty"`
	// supported_signals lists every signal the scorer can return.
	SupportedSignals []ScoreSignal `protobuf:"varint,4,rep,packed,name=supported_signals,json=supportedSignals,proto3,enum=finfocus.v1.ScoreSignal" json:"supported_signals,omitempty"`
	// session_id echoes the request session_id when the scorer honors sessions.
	// Empty means the scorer declined, and duplicate_group_id is scoped to this
	// response only. A non-empty value that differs from the request is invalid.
	SessionId     string `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreRecommendationsResponse) Reset() {
	*x = ScoreRecommendationsResponse{}
	mi := &file_finfocus_v1_scoring_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreRecommendationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreRecommendationsResponse) ProtoMessage() {}

func (x *ScoreRecommendationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finfocus_v1_scoring_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreRecommendationsResponse.ProtoReflect.Descriptor instead.
func (*ScoreRecommendationsResponse) Descriptor() ([]byte, []int) {
	return file_finfocus_v1_scoring_proto_rawDescGZIP(), []int{1}
}

func (x *ScoreRecommendationsResponse) GetResults() []*RecommendationScoreResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ScoreRecommendationsResponse) GetMaxBatchSize() int32 {
	if x != nil {
		return x.MaxBatchSize
	}
	return 0
}

func (x *ScoreRecommendationsResponse) GetScorer() *ScorerInfo {
	if x != nil {
		return x.Scorer
	}
	return nil
}

func (x *ScoreRecommendationsResponse) GetSupportedSignals() []ScoreSignal {
	if x != nil {
		return x.SupportedSignals
	}
	return nil
}

func (x *ScoreRecommendationsResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// RecommendationScoreResult is the outcome for one recommendation.
type RecommendationScoreResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// recommendation_id echoes Recommendation.id.
	RecommendationId string `protobuf:"bytes,1,opt,name=recommendation_id,json=recommendationId,proto3" json:"recommendation_id,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*RecommendationScoreResult_Scores
	//	*RecommendationScoreResult_Error
	Result        isRecommendationScoreResult_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendationScoreResult) Reset() {
	*x = RecommendationScoreResult{}
	mi := &file_finfocus_v1_scoring_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationScoreResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationScoreResult) ProtoMessage() {}

func (x *RecommendationScoreResult) ProtoReflect() protoreflect.Message {
	mi := &file_finfocus_v1_scoring_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationScoreResult.ProtoReflect.Descriptor instead.
func (*RecommendationScoreResult) Descriptor() ([]byte, []int) {
	return file_finfocus_v1_scoring_proto_rawDescGZIP(), []int{2}
}

func (x *RecommendationScoreResult) GetRecommendationId() string {
	if x != nil {
		return x.RecommendationId
	}
	return ""
}

func (x *RecommendationScoreResult) GetResult() isRecommendationScoreResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *RecommendationScoreResult) GetScores() *RecommendationScores {
	if x != nil {
		if x, ok := x.Result.(*RecommendationScoreResult_Scores); ok {
			return x.Scores
		}
	}
	return nil
}

func (x *RecommendationScoreResult) GetError() *ResourceError {
	if x != nil {
		if x, ok := x.Result.(*RecommendationScoreResult_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isRecommendationScoreResult_Result interface {
	isRecommendationScoreResult_Result()
}

type RecommendationScoreResult_Scores struct {
	// scores holds the requested signals.
	Scores *RecommendationScores `protobuf:"bytes,2,opt,name=scores,proto3,oneof"`
}

type RecommendationScoreResult_Error struct {
	// error reports why this recommendation could not be scored. The code is a
	// google.rpc.Code and is never OK.
	Error *ResourceError `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*RecommendationScoreResult_Scores) isRecommendationScoreResult_Result() {}

func (*RecommendationScoreResult_Error) isRecommendationScoreResult_Result() {}

// RecommendationScores holds the signals for one recommendation. A signal the
// scorer did not compute is unset.
type RecommendationScores struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// risk is in [0, 1]; see SCORE_SIGNAL_RISK.
	Risk *float64 `protobuf:"fixed64,1,opt,name=risk,proto3,oneof" json:"risk,omitempty"`
	// false_positive is in [0, 1]; see SCORE_SIGNAL_FALSE_POSITIVE.
	FalsePositive *float64 `protobuf:"fixed64,2,opt,name=false_positive,json=falsePositive,proto3,oneof" json:"false_positive,omitempty"`
	// worth_acting is in [0, 1]; see SCORE_SIGNAL_WORTH_ACTING.
	WorthActing *float64 `protobuf:"fixed64,3,opt,name=worth_acting,json=worthActing,proto3,oneof" json:"worth_acting,omitempty"`
	// priority is in [0, 3]; see SCORE_SIGNAL_PRIORITY.
	Priority *float64 `protobuf:"fixed64,4,opt,name=priority,proto3,oneof" json:"priority,omitempty"`
	// insufficient_evidence is in [0, 1]; see SCORE_SIGNAL_INSUFFICIENT_EVIDENCE.
	InsufficientEvidence *float64 `protobuf:"fixed64,5,opt,name=insufficient_evidence,json=insufficientEvidence,proto3,oneof" json:"insufficient_evidence,omitempty"`
	// duplicate_group_id is the same non-empty string for every recommendation in
	// the request that duplicates each other. Empty means no duplicate found or
	// grouping not performed. Without a session the value is meaningful only
	// within one response and is shared by at least two recommendations. With a
	// session (the response echoes session_id) it is a deterministic function of
	// session_id and the duplicate key, so equal values across the responses of
	// one session name one group, and one response may hold a single member.
	// Hosts never cache it per recommendation.
	DuplicateGroupId string `protobuf:"bytes,6,opt,name=duplicate_group_id,json=duplicateGroupId,proto3" json:"duplicate_group_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RecommendationScores) Reset() {
	*x = RecommendationScores{}
	mi := &file_finfocus_v1_scoring_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationScores) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationScores) ProtoMessage() {}

func (x *RecommendationScores) ProtoReflect() protoreflect.Message {
	mi := &file_finfocus_v1_scoring_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationScores.ProtoReflect.Descriptor instead.
func (*RecommendationScores) Descriptor() ([]byte, []int) {
	return file_finfocus_v1_scoring_proto_rawDescGZIP(), []int{3}
}

func (x *RecommendationScores) GetRisk() float64 {
	if x != nil && x.Risk != nil {
		return *x.Risk
	}
	return 0
}

func (x *RecommendationScores) GetFalsePositive() float64 {
	if x != nil && x.FalsePositive != nil {
		return *x.FalsePositive
	}
	return 0
}

func (x *RecommendationScores) GetWorthActing() float64 {
	if x != nil && x.WorthActing != nil {
		return *x.WorthActing
	}
	return 0
}

func (x *RecommendationScores) GetPriority() float64 {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return 0
}

func (x *RecommendationScores) GetInsufficientEvidence() float64 {
	if x != nil && x.InsufficientEvidence != nil {
		return *x.InsufficientEvidence
	}
	return 0
}

func (x *RecommendationScores) GetDuplicateGroupId() string {
	if x != nil {
		return x.DuplicateGroupId
	}
	return ""
}

// ScorerInfo identifies a scorer and how to read its numbers.
type ScorerInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the scorer implementation, for example "jev".
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// model is the model or engine behind it, for example "jev-1.13.0". Empty
	// for scorers that use no model.
	Model string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	// calibration says whether numeric signals are probabilities.
	Calibration ScoreCalibration `protobuf:"varint,3,opt,name=calibration,proto3,enum=finfocus.v1.ScoreCalibration" json:"calibration,omitempty"`
	// provider_request_id is the backend's request identifier, for support
	// tickets. Empty when there is none.
	ProviderRequestId string `protobuf:"bytes,4,opt,name=provider_request_id,json=providerRequestId,proto3" json:"provider_request_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ScorerInfo) Reset() {
	*x = ScorerInfo{}
	mi := &file_finfocus_v1_scoring_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScorerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScorerInfo) ProtoMessage() {}

func (x *ScorerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_finfocus_v1_scoring_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScorerInfo.ProtoReflect.Descriptor instead.
func (*ScorerInfo) Descriptor() ([]byte, []int) {
	return file_finfocus_v1_scoring_proto_rawDescGZIP(), []int{4}
}

func (x *ScorerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScorerInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ScorerInfo) GetCalibration() ScoreCalibration {
	if x != nil {
		return x.Calibration
	}
	return ScoreCalibration_SCORE_CALIBRATION_UNSPECIFIED
}

func (x *ScorerInfo) GetProviderRequestId() string {
	if x != nil {
		return x.ProviderRequestId
	}
	return ""
}

var File_finfocus_v1_scoring_proto protoreflect.FileDescriptor

const file_finfocus_v1_scoring_proto_rawDesc = "" +
	"\n" +
	"\x19finfocus/v1/scoring.proto\x12\vfinfocus.v1\x1a\x1cfinfocus/v1/costsource.proto\"\xfd\x01\n" +
	"\x1bScoreRecommendationsRequest\x12E\n" +
	"\x0frecommendations\x18\x01 \x03(\v2\x1b.finfocus.v1.RecommendationR\x0frecommendations\x122\n" +
	"\asignals\x18\x02 \x03(\x0e2\x18.finfocus.v1.ScoreSignalR\asignals\x12D\n" +
	"\x0fidentifier_mode\x18\x03 \x01(\x0e2\x1b.finfocus.v1.IdentifierModeR\x0eidentifierMode\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\"\x9d\x02\n" +
	"\x1cScoreRecommendationsResponse\x12@\n" +
	"\aresults\x18\x01 \x03(\v2&.finfocus.v1.RecommendationScoreResultR\aresults\x12$\n" +
	"\x0emax_batch_size\x18\x02 \x01(\x05R\fmaxBatchSize\x12/\n" +
	"\x06scorer\x18\x03 \x01(\v2\x17.finfocus.v1.ScorerInfoR\x06scorer\x12E\n" +
	"\x11supported_signals\x18\x04 \x03(\x0e2\x18.finfocus.v1.ScoreSignalR\x10supportedSignals\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\"\xc3\x01\n" +
	"\x19RecommendationScoreResult\x12+\n" +
	"\x11recommendation_id\x18\x01 \x01(\tR\x10recommendationId\x12;\n" +
	"\x06scores\x18\x02 \x01(\v2!.finfocus.v1.RecommendationScoresH\x00R\x06scores\x122\n" +
	"\x05error\x18\x03 \x01(\v2\x1a.finfocus.v1.ResourceErrorH\x00R\x05errorB\b\n" +
	"\x06result\"\xe0\x02\n" +
	"\x14RecommendationScores\x12\x17\n" +
	"\x04risk\x18\x01 \x01(\x01H\x00R\x04risk\x88\x01\x01\x12*\n" +
	"\x0efalse_positive\x18\x02 \x01(\x01H\x01R\rfalsePositive\x88\x01\x01\x12&\n" +
	"\fworth_acting\x18\x03 \x01(\x01H\x02R\vworthActing\x88\x01\x01\x12\x1f\n" +
	"\bpriority\x18\x04 \x01(\x01H\x03R\bpriority\x88\x01\x01\x128\n" +
	"\x15insufficient_evidence\x18\x05 \x01(\x01H\x04R\x14insufficientEvidence\x88\x01\x01\x12,\n" +
	"\x12duplicate_group_id\x18\x06 \x01(\tR\x10duplicateGroupIdB\a\n" +
	"\x05_riskB\x11\n" +
	"\x0f_false_positiveB\x0f\n" +
	"\r_worth_actingB\v\n" +
	"\t_priorityB\x18\n" +
	"\x16_insufficient_evidence\"\xa7\x01\n" +
	"\n" +
	"ScorerInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12?\n" +
	"\vcalibration\x18\x03 \x01(\x0e2\x1d.finfocus.v1.ScoreCalibrationR\vcalibration\x12.\n" +
	"\x13provider_request_id\x18\x04 \x01(\tR\x11providerRequestId*\xe7\x01\n" +
	"\vScoreSignal\x12\x1c\n" +
	"\x18SCORE_SIGNAL_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11SCORE_SIGNAL_RISK\x10\x01\x12\x1f\n" +
	"\x1bSCORE_SIGNAL_FALSE_POSITIVE\x10\x02\x12\x1d\n" +
	"\x19SCORE_SIGNAL_WORTH_ACTING\x10\x03\x12\x19\n" +
	"\x15SCORE_SIGNAL_PRIORITY\x10\x04\x12&\n" +
	"\"SCORE_SIGNAL_INSUFFICIENT_EVIDENCE\x10\x05\x12 \n" +
	"\x1cSCORE_SIGNAL_DUPLICATE_GROUP\x10\x06*|\n" +
	"\x10ScoreCalibration\x12!\n" +
	"\x1dSCORE_CALIBRATION_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eSCORE_CALIBRATION_RANKING_ONLY\x10\x01\x12!\n" +
	"\x1dSCORE_CALIBRATION_PROBABILITY\x10\x02*\x8a\x01\n" +
	"\x0eIdentifierMode\x12\x1f\n" +
	"\x1bIDENTIFIER_MODE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13IDENTIFIER_MODE_RAW\x10\x01\x12!\n" +
	"\x1dIDENTIFIER_MODE_PSEUDONYMIZED\x10\x02\x12\x1b\n" +
	"\x17IDENTIFIER_MODE_OMITTED\x10\x032\x8a\x01\n" +
	"\x1bRecommendationScorerService\x12k\n" +
	"\x14ScoreRecommendations\x12(.finfocus.v1.ScoreRecommendationsRequest\x1a).finfocus.v1.ScoreRecommendationsResponseB\xaa\x01\n" +
	"\x0fcom.finfocus.v1B\fScoringProtoP\x01Z<github.com/rshade/finfocus-spec/sdk/go/proto/finfocus/v1;pbc\xa2\x02\x03FXX\xaa\x02\vFinfocus.V1\xca\x02\vFinfocus\\V1\xe2\x02\x17Finfocus\\V1\\GPBMetadata\xea\x02\fFinfocus::V1b\x06proto3"

var (
	file_finfocus_v1_scoring_proto_rawDescOnce sync.Once
	file_finfocus_v1_scoring_proto_rawDescData []byte
)

func file_finfocus_v1_scoring_proto_rawDescGZIP() []byte {
	file_finfocus_v1_scoring_proto_rawDescOnce.Do(func() {
		file_finfocus_v1_scoring_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_finfocus_v1_scoring_proto_rawDesc), len(file_finfocus_v1_scoring_proto_rawDesc)))
	})
	return file_finfocus_v1_scoring_proto_rawDescData
}

var file_finfocus_v1_scoring_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_finfocus_v1_scoring_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_finfocus_v1_scoring_proto_goTypes = []any{
	(ScoreSignal)(0),                     // 0: finfocus.v1.ScoreSignal
	(ScoreCalibration)(0),                // 1: finfocus.v1.ScoreCalibration
	(IdentifierMode)(0),                  // 2: finfocus.v1.IdentifierMode
	(*ScoreRecommendationsRequest)(nil),  // 3: finfocus.v1.ScoreRecommendationsRequest
	(*ScoreRecommendationsResponse)(nil), // 4: finfocus.v1.ScoreRecommendationsResponse
	(*RecommendationScoreResult)(nil),    // 5: finfocus.v1.RecommendationScoreResult
	(*RecommendationScores)(nil),         // 6: finfocus.v1.RecommendationScores
	(*ScorerInfo)(nil),                   // 7: finfocus.v1.ScorerInfo
	(*Recommendation)(nil),               // 8: finfocus.v1.Recommendation
	(*ResourceError)(nil),                // 9: finfocus.v1.ResourceError
}
var file_finfocus_v1_scoring_proto_depIdxs = []int32{
	8,  // 0: finfocus.v1.ScoreRecommendationsRequest.recommendations:type_name -> finfocus.v1.Recommendation
	0,  // 1: finfocus.v1.ScoreRecommendationsRequest.signals:type_name -> finfocus.v1.ScoreSignal
	2,  // 2: finfocus.v1.ScoreRecommendationsRequest.identifier_mode:type_name -> finfocus.v1.IdentifierMode
	5,  // 3: finfocus.v1.ScoreRecommendationsResponse.results:type_name -> finfocus.v1.RecommendationScoreResult
	7,  // 4: finfocus.v1.ScoreRecommendationsResponse.scorer:type_name -> finfocus.v1.ScorerInfo
	0,  // 5: finfocus.v1.ScoreRecommendationsResponse.supported_signals:type_name -> finfocus.v1.ScoreSignal
	6,  // 6: finfocus.v1.RecommendationScoreResult.scores:type_name -> finfocus.v1.RecommendationScores
	9,  // 7: finfocus.v1.RecommendationScoreResult.error:type_name -> finfocus.v1.ResourceError
	1,  // 8: finfocus.v1.ScorerInfo.calibration:type_name -> finfocus.v1.ScoreCalibration
	3,  // 9: finfocus.v1.RecommendationScorerService.ScoreRecommendations:input_type -> finfocus.v1.ScoreRecommendationsRequest
	4,  // 10: finfocus.v1.RecommendationScorerService.ScoreRecommendations:output_type -> finfocus.v1.ScoreRecommendationsResponse
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_finfocus_v1_scoring_proto_init() }
func file_finfocus_v1_scoring_proto_init() {
	if File_finfocus_v1_scoring_proto != nil {
		return
	}
	file_finfocus_v1_costsource_proto_init()
	file_finfocus_v1_scoring_proto_msgTypes[2].OneofWrappers = []any{
		(*RecommendationScoreResult_Scores)(nil),
		(*RecommendationScoreResult_Error)(nil),
	}
	file_finfocus_v1_scoring_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_finfocus_v1_scoring_proto_rawDesc), len(file_finfocus_v1_scoring_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_finfocus_v1_scoring_proto_goTypes,
		DependencyIndexes: file_finfocus_v1_scoring_proto_depIdxs,
		EnumInfos:         file_finfocus_v1_scoring_proto_enumTypes,
		MessageInfos:      file_finfocus_v1_scoring_proto_msgTypes,
	}.Build()
	File_finfocus_v1_scoring_proto = out.File
	file_finfocus_v1_scoring_proto_goTypes = nil
	file_finfocus_v1_scoring_proto_depIdxs = nil
}
