// Copyright 2026 The FinFocus Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: finfocus/v1/supplemental.proto

package pbc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetContractCommitmentsRequest selects commitments by time window and page.
//
// Window matching: a commitment's period is its contract commitment period
// when either contract_commitment_period_start or _end is set, otherwise its
// contract period. Periods and the window are half-open [start, end). An unset
// period bound is open-ended, and a commitment with no period bounds matches
// every window. A commitment matches when its period overlaps the window.
type GetContractCommitmentsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Start of the window (inclusive). Leave both start and end unset to
	// request every commitment; setting exactly one is INVALID_ARGUMENT.
	Start *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	// End of the window (exclusive). Must be after start.
	End *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	// Maximum number of commitments to return. 0 means the default of 50;
	// values above 1000 are served as 1000; negative values are
	// INVALID_ARGUMENT. There is no "return everything" mode.
	PageSize int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Continuation token from a previous response's next_page_token; empty for
	// the first page. Tokens are OPAQUE: clients pass them back verbatim with
	// the same start, end, and page_size, and never construct them.
	PageToken     string `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContractCommitmentsRequest) Reset() {
	*x = GetContractCommitmentsRequest{}
	mi := &file_finfocus_v1_supplemental_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContractCommitmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContractCommitmentsRequest) ProtoMessage() {}

func (x *GetContractCommitmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finfocus_v1_supplemental_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContractCommitmentsRequest.ProtoReflect.Descriptor instead.
func (*GetContractCommitmentsRequest) Descriptor() ([]byte, []int) {
	return file_finfocus_v1_supplemental_proto_rawDescGZIP(), []int{0}
}

func (x *GetContractCommitmentsRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *GetContractCommitmentsRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *GetContractCommitmentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetContractCommitmentsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// GetContractCommitmentsResponse carries one page of commitments.
type GetContractCommitmentsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Commitments on this page, in an order that is stable across calls. Each
	// record is valid by the SDK's ContractCommitment rules, and
	// contract_commitment_id is unique within the response and across the pages
	// of one walk.
	Commitments []*ContractCommitment `protobuf:"bytes,1,rep,name=commitments,proto3" json:"commitments,omitempty"`
	// Token for the next page; empty on the last page. OPAQUE.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// Exact number of commitments matching the window across all pages; 0 only
	// when none match.
	TotalCount    int32 `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContractCommitmentsResponse) Reset() {
	*x = GetContractCommitmentsResponse{}
	mi := &file_finfocus_v1_supplemental_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContractCommitmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContractCommitmentsResponse) ProtoMessage() {}

func (x *GetContractCommitmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finfocus_v1_supplemental_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContractCommitmentsResponse.ProtoReflect.Descriptor instead.
func (*GetContractCommitmentsResponse) Descriptor() ([]byte, []int) {
	return file_finfocus_v1_supplemental_proto_rawDescGZIP(), []int{1}
}

func (x *GetContractCommitmentsResponse) GetCommitments() []*ContractCommitment {
	if x != nil {
		return x.Commitments
	}
	return nil
}

func (x *GetContractCommitmentsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *GetContractCommitmentsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_finfocus_v1_supplemental_proto protoreflect.FileDescriptor

const file_finfocus_v1_supplemental_proto_rawDesc = "" +
	"\n" +
	"\x1efinfocus/v1/supplemental.proto\x12\vfinfocus.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17finfocus/v1/focus.proto\"\xbb\x01\n" +
	"\x1dGetContractCommitmentsRequest\x120\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"\xac\x01\n" +
	"\x1eGetContractCommitmentsResponse\x12A\n" +
	"\vcommitments\x18\x01 \x03(\v2\x1f.finfocus.v1.ContractCommitmentR\vcommitments\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount2\x8f\x01\n" +
	"\x1aSupplementalDatasetService\x12q\n" +
	"\x16GetContractCommitments\x12*.finfocus.v1.GetContractCommitmentsRequest\x1a+.finfocus.v1.GetContractCommitmentsResponseB\xaf\x01\n" +
	"\x0fcom.finfocus.v1B\x11SupplementalProtoP\x01Z<github.com/rshade/finfocus-spec/sdk/go/proto/finfocus/v1;pbc\xa2\x02\x03FXX\xaa\x02\vFinfocus.V1\xca\x02\vFinfocus\\V1\xe2\x02\x17Finfocus\\V1\\GPBMetadata\xea\x02\fFinfocus::V1b\x06proto3"

var (
	file_finfocus_v1_supplemental_proto_rawDescOnce sync.Once
	file_finfocus_v1_supplemental_proto_rawDescData []byte
)

func file_finfocus_v1_supplemental_proto_rawDescGZIP() []byte {
	file_finfocus_v1_supplemental_proto_rawDescOnce.Do(func() {
		file_finfocus_v1_supplemental_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_finfocus_v1_supplemental_proto_rawDesc), len(file_finfocus_v1_supplemental_proto_rawDesc)))
	})
	return file_finfocus_v1_supplemental_proto_rawDescData
}

var file_finfocus_v1_supplemental_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_finfocus_v1_supplemental_proto_goTypes = []any{
	(*GetContractCommitmentsRequest)(nil),  // 0: finfocus.v1.GetContractCommitmentsRequest
	(*GetContractCommitmentsResponse)(nil), // 1: finfocus.v1.GetContractCommitmentsResponse
	(*timestamppb.Timestamp)(nil),          // 2: google.protobuf.Timestamp
	(*ContractCommitment)(nil),             // 3: finfocus.v1.ContractCommitment
}
var file_finfocus_v1_supplemental_proto_depIdxs = []int32{
	2, // 0: finfocus.v1.GetContractCommitmentsRequest.start:type_name -> google.protobuf.Timestamp
	2, // 1: finfocus.v1.GetContractCommitmentsRequest.end:type_name -> google.protobuf.Timestamp
	3, // 2: finfocus.v1.GetContractCommitmentsResponse.commitments:type_name -> finfocus.v1.ContractCommitment
	0, // 3: finfocus.v1.SupplementalDatasetService.GetContractCommitments:input_type -> finfocus.v1.GetContractCommitmentsRequest
	1, // 4: finfocus.v1.SupplementalDatasetService.GetContractCommitments:output_type -> finfocus.v1.GetContractCommitmentsResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_finfocus_v1_supplemental_proto_init() }
func file_finfocus_v1_supplemental_proto_init() {
	if File_finfocus_v1_supplemental_proto != nil {
		return
	}
	file_finfocus_v1_focus_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_finfocus_v1_supplemental_proto_rawDesc), len(file_finfocus_v1_supplemental_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_finfocus_v1_supplemental_proto_goTypes,
		DependencyIndexes: file_finfocus_v1_supplemental_proto_depIdxs,
		MessageInfos:      file_finfocus_v1_supplemental_proto_msgTypes,
	}.Build()
	File_finfocus_v1_supplemental_proto = out.File
	file_finfocus_v1_supplemental_proto_goTypes = nil
	file_finfocus_v1_supplemental_proto_depIdxs = nil
}
