// Copyright 2026 The FinFocus Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: finfocus/v1/supplemental.proto

package pbc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SupplementalDatasetService_GetContractCommitments_FullMethodName = "/finfocus.v1.SupplementalDatasetService/GetContractCommitments"
)

// SupplementalDatasetServiceClient is the client API for SupplementalDatasetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SupplementalDatasetService is implemented by plugins that deliver FOCUS
// supplemental datasets: records that sit beside Cost and Usage rows and join
// to them by key. Each dataset has its own RPC and its own plugin capability,
// so a plugin serves only the datasets it has. Stage A defines Contract
// Commitment (FOCUS 1.3); PLUGIN_CAPABILITY_CONTRACT_COMMITMENTS advertises it.
//
// Every call returns the source's current view of the requested records
// (FOCUS Replacement / Overwrite semantics): a host replaces what it holds for
// the same window rather than appending.
//
// Error semantics:
//   - INVALID_ARGUMENT: only one of start/end is set, a timestamp is invalid,
//     end is not after start, page_size is negative, or page_token was not
//     issued by this source.
//   - PERMISSION_DENIED: credentials lack a required permission.
//   - UNAUTHENTICATED: no usable credentials.
type SupplementalDatasetServiceClient interface {
	// GetContractCommitments returns a page of FOCUS Contract Commitment records
	// whose period overlaps the requested window.
	GetContractCommitments(ctx context.Context, in *GetContractCommitmentsRequest, opts ...grpc.CallOption) (*GetContractCommitmentsResponse, error)
}

type supplementalDatasetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSupplementalDatasetServiceClient(cc grpc.ClientConnInterface) SupplementalDatasetServiceClient {
	return &supplementalDatasetServiceClient{cc}
}

func (c *supplementalDatasetServiceClient) GetContractCommitments(ctx context.Context, in *GetContractCommitmentsRequest, opts ...grpc.CallOption) (*GetContractCommitmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContractCommitmentsResponse)
	err := c.cc.Invoke(ctx, SupplementalDatasetService_GetContractCommitments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SupplementalDatasetServiceServer is the server API for SupplementalDatasetService service.
// All implementations must embed UnimplementedSupplementalDatasetServiceServer
// for forward compatibility.
//
// SupplementalDatasetService is implemented by plugins that deliver FOCUS
// supplemental datasets: records that sit beside Cost and Usage rows and join
// to them by key. Each dataset has its own RPC and its own plugin capability,
// so a plugin serves only the datasets it has. Stage A defines Contract
// Commitment (FOCUS 1.3); PLUGIN_CAPABILITY_CONTRACT_COMMITMENTS advertises it.
//
// Every call returns the source's current view of the requested records
// (FOCUS Replacement / Overwrite semantics): a host replaces what it holds for
// the same window rather than appending.
//
// Error semantics:
//   - INVALID_ARGUMENT: only one of start/end is set, a timestamp is invalid,
//     end is not after start, page_size is negative, or page_token was not
//     issued by this source.
//   - PERMISSION_DENIED: credentials lack a required permission.
//   - UNAUTHENTICATED: no usable credentials.
type SupplementalDatasetServiceServer interface {
	// GetContractCommitments returns a page of FOCUS Contract Commitment records
	// whose period overlaps the requested window.
	GetContractCommitments(context.Context, *GetContractCommitmentsRequest) (*GetContractCommitmentsResponse, error)
	mustEmbedUnimplementedSupplementalDatasetServiceServer()
}

// UnimplementedSupplementalDatasetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSupplementalDatasetServiceServer struct{}

func (UnimplementedSupplementalDatasetServiceServer) GetContractCommitments(context.Context, *GetContractCommitmentsRequest) (*GetContractCommitmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContractCommitments not implemented")
}
func (UnimplementedSupplementalDatasetServiceServer) mustEmbedUnimplementedSupplementalDatasetServiceServer() {
}
func (UnimplementedSupplementalDatasetServiceServer) testEmbeddedByValue() {}

// UnsafeSupplementalDatasetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SupplementalDatasetServiceServer will
// result in compilation errors.
type UnsafeSupplementalDatasetServiceServer interface {
	mustEmbedUnimplementedSupplementalDatasetServiceServer()
}

func RegisterSupplementalDatasetServiceServer(s grpc.ServiceRegistrar, srv SupplementalDatasetServiceServer) {
	// If the following call panics, it indicates UnimplementedSupplementalDatasetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SupplementalDatasetService_ServiceDesc, srv)
}

func _SupplementalDatasetService_GetContractCommitments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContractCommitmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplementalDatasetServiceServer).GetContractCommitments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupplementalDatasetService_GetContractCommitments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplementalDatasetServiceServer).GetContractCommitments(ctx, req.(*GetContractCommitmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SupplementalDatasetService_ServiceDesc is the grpc.ServiceDesc for SupplementalDatasetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SupplementalDatasetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "finfocus.v1.SupplementalDatasetService",
	HandlerType: (*SupplementalDatasetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetContractCommitments",
			Handler:    _SupplementalDatasetService_GetContractCommitments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "finfocus/v1/supplemental.proto",
}
