// Copyright 2026 The FinFocus Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: finfocus/v1/supplemental.proto

package pbc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetContractCommitmentsRequest selects commitments by time window and page.
//
// Window matching: a commitment's period is its contract commitment period
// when either contract_commitment_period_start or _end is set, otherwise its
// contract period. Periods and the window are half-open [start, end). An unset
// period bound is open-ended, and a commitment with no period bounds matches
// every window. A commitment matches when its period overlaps the window.
type GetContractCommitmentsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Start of the window (inclusive). Leave both start and end unset to
	// request every commitment; setting exactly one is INVALID_ARGUMENT.
	Start *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	// End of the window (exclusive). Must be after start.
	End *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	// Maximum number of commitments to return. 0 means the default of 50;
	// values above 1000 are served as 1000; negative values are
	// INVALID_ARGUMENT. There is no "return everything" mode.
	PageSize int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Continuation token from a previous response's next_page_token; empty for
	// the first page. Tokens are OPAQUE: clients pass them back verbatim with
	// the same start, end, and page_size, and never construct them.
	PageToken     string `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContractCommitmentsRequest) Reset() {
	*x = GetContractCommitmentsRequest{}
	mi := &file_finfocus_v1_supplemental_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContractCommitmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContractCommitmentsRequest) ProtoMessage() {}

func (x *GetContractCommitmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finfocus_v1_supplemental_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContractCommitmentsRequest.ProtoReflect.Descriptor instead.
func (*GetContractCommitmentsRequest) Descriptor() ([]byte, []int) {
	return file_finfocus_v1_supplemental_proto_rawDescGZIP(), []int{0}
}

func (x *GetContractCommitmentsRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *GetContractCommitmentsRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *GetContractCommitmentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetContractCommitmentsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// GetContractCommitmentsResponse carries one page of commitments.
type GetContractCommitmentsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Commitments on this page, in an order that is stable across calls. Each
	// record is valid by the SDK's ContractCommitment rules, and
	// contract_commitment_id is unique within the response and across the pages
	// of one walk.
	Commitments []*ContractCommitment `protobuf:"bytes,1,rep,name=commitments,proto3" json:"commitments,omitempty"`
	// Token for the next page; empty on the last page. OPAQUE.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// Exact number of commitments matching the window across all pages; 0 only
	// when none match.
	TotalCount    int32 `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContractCommitmentsResponse) Reset() {
	*x = GetContractCommitmentsResponse{}
	mi := &file_finfocus_v1_supplemental_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContractCommitmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContractCommitmentsResponse) ProtoMessage() {}

func (x *GetContractCommitmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finfocus_v1_supplemental_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContractCommitmentsResponse.ProtoReflect.Descriptor instead.
func (*GetContractCommitmentsResponse) Descriptor() ([]byte, []int) {
	return file_finfocus_v1_supplemental_proto_rawDescGZIP(), []int{1}
}

func (x *GetContractCommitmentsResponse) GetCommitments() []*ContractCommitment {
	if x != nil {
		return x.Commitments
	}
	return nil
}

func (x *GetContractCommitmentsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *GetContractCommitmentsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// GetBillingPeriodsRequest selects billing periods by time window and page.
// The window rules match GetContractCommitmentsRequest: both bounds or
// neither, half-open [start, end), page_size 0 means 50, above 1000 clamps,
// negative is INVALID_ARGUMENT, and page_token is opaque.
type GetBillingPeriodsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Start of the window (inclusive). Leave both start and end unset to
	// request every billing period; setting exactly one is INVALID_ARGUMENT.
	Start *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	// End of the window (exclusive). Must be after start.
	End *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	// Maximum number of billing periods to return. 0 means the default of 50;
	// values above 1000 are served as 1000; negative values are
	// INVALID_ARGUMENT.
	PageSize int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Continuation token from a previous response's next_page_token; empty for
	// the first page. OPAQUE.
	PageToken     string `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBillingPeriodsRequest) Reset() {
	*x = GetBillingPeriodsRequest{}
	mi := &file_finfocus_v1_supplemental_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBillingPeriodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillingPeriodsRequest) ProtoMessage() {}

func (x *GetBillingPeriodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finfocus_v1_supplemental_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillingPeriodsRequest.ProtoReflect.Descriptor instead.
func (*GetBillingPeriodsRequest) Descriptor() ([]byte, []int) {
	return file_finfocus_v1_supplemental_proto_rawDescGZIP(), []int{2}
}

func (x *GetBillingPeriodsRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *GetBillingPeriodsRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *GetBillingPeriodsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetBillingPeriodsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// GetBillingPeriodsResponse carries one page of billing periods.
type GetBillingPeriodsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Billing periods on this page, in an order that is stable across calls.
	// Each record passes the BillingPeriod rules, overlaps the window, and the
	// pair (invoice_issuer_name, billing_period_start) is unique within the
	// response and across the pages of one walk.
	BillingPeriods []*BillingPeriod `protobuf:"bytes,1,rep,name=billing_periods,json=billingPeriods,proto3" json:"billing_periods,omitempty"`
	// Token for the next page; empty on the last page. OPAQUE.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// Exact number of billing periods matching the window across all pages.
	TotalCount    int32 `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBillingPeriodsResponse) Reset() {
	*x = GetBillingPeriodsResponse{}
	mi := &file_finfocus_v1_supplemental_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBillingPeriodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillingPeriodsResponse) ProtoMessage() {}

func (x *GetBillingPeriodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finfocus_v1_supplemental_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillingPeriodsResponse.ProtoReflect.Descriptor instead.
func (*GetBillingPeriodsResponse) Descriptor() ([]byte, []int) {
	return file_finfocus_v1_supplemental_proto_rawDescGZIP(), []int{3}
}

func (x *GetBillingPeriodsResponse) GetBillingPeriods() []*BillingPeriod {
	if x != nil {
		return x.BillingPeriods
	}
	return nil
}

func (x *GetBillingPeriodsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *GetBillingPeriodsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// GetInvoiceDetailsRequest selects invoice lines by time window and page.
// The window rules match GetBillingPeriodsRequest.
type GetInvoiceDetailsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Start of the window (inclusive). Leave both start and end unset to
	// request every invoice line; setting exactly one is INVALID_ARGUMENT.
	Start *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	// End of the window (exclusive). Must be after start.
	End *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	// Maximum number of invoice lines to return. 0 means the default of 50;
	// values above 1000 are served as 1000; negative values are
	// INVALID_ARGUMENT.
	PageSize int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Continuation token from a previous response's next_page_token; empty for
	// the first page. OPAQUE.
	PageToken     string `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvoiceDetailsRequest) Reset() {
	*x = GetInvoiceDetailsRequest{}
	mi := &file_finfocus_v1_supplemental_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvoiceDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvoiceDetailsRequest) ProtoMessage() {}

func (x *GetInvoiceDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finfocus_v1_supplemental_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvoiceDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetInvoiceDetailsRequest) Descriptor() ([]byte, []int) {
	return file_finfocus_v1_supplemental_proto_rawDescGZIP(), []int{4}
}

func (x *GetInvoiceDetailsRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *GetInvoiceDetailsRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *GetInvoiceDetailsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetInvoiceDetailsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// GetInvoiceDetailsResponse carries one page of invoice lines.
type GetInvoiceDetailsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Invoice lines on this page, in an order that is stable across calls.
	// Each record passes the InvoiceDetail rules, its billing period overlaps
	// the window, and invoice_detail_id is unique within the response and
	// across the pages of one walk.
	InvoiceDetails []*InvoiceDetail `protobuf:"bytes,1,rep,name=invoice_details,json=invoiceDetails,proto3" json:"invoice_details,omitempty"`
	// Token for the next page; empty on the last page. OPAQUE.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// Exact number of invoice lines matching the window across all pages.
	TotalCount    int32 `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvoiceDetailsResponse) Reset() {
	*x = GetInvoiceDetailsResponse{}
	mi := &file_finfocus_v1_supplemental_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvoiceDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvoiceDetailsResponse) ProtoMessage() {}

func (x *GetInvoiceDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finfocus_v1_supplemental_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvoiceDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetInvoiceDetailsResponse) Descriptor() ([]byte, []int) {
	return file_finfocus_v1_supplemental_proto_rawDescGZIP(), []int{5}
}

func (x *GetInvoiceDetailsResponse) GetInvoiceDetails() []*InvoiceDetail {
	if x != nil {
		return x.InvoiceDetails
	}
	return nil
}

func (x *GetInvoiceDetailsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *GetInvoiceDetailsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_finfocus_v1_supplemental_proto protoreflect.FileDescriptor

const file_finfocus_v1_supplemental_proto_rawDesc = "" +
	"\n" +
	"\x1efinfocus/v1/supplemental.proto\x12\vfinfocus.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17finfocus/v1/focus.proto\"\xbb\x01\n" +
	"\x1dGetContractCommitmentsRequest\x120\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"\xac\x01\n" +
	"\x1eGetContractCommitmentsResponse\x12A\n" +
	"\vcommitments\x18\x01 \x03(\v2\x1f.finfocus.v1.ContractCommitmentR\vcommitments\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"\xb6\x01\n" +
	"\x18GetBillingPeriodsRequest\x120\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"\xa9\x01\n" +
	"\x19GetBillingPeriodsResponse\x12C\n" +
	"\x0fbilling_periods\x18\x01 \x03(\v2\x1a.finfocus.v1.BillingPeriodR\x0ebillingPeriods\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"\xb6\x01\n" +
	"\x18GetInvoiceDetailsRequest\x120\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"\xa9\x01\n" +
	"\x19GetInvoiceDetailsResponse\x12C\n" +
	"\x0finvoice_details\x18\x01 \x03(\v2\x1a.finfocus.v1.InvoiceDetailR\x0einvoiceDetails\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount2\xd7\x02\n" +
	"\x1aSupplementalDatasetService\x12q\n" +
	"\x16GetContractCommitments\x12*.finfocus.v1.GetContractCommitmentsRequest\x1a+.finfocus.v1.GetContractCommitmentsResponse\x12b\n" +
	"\x11GetBillingPeriods\x12%.finfocus.v1.GetBillingPeriodsRequest\x1a&.finfocus.v1.GetBillingPeriodsResponse\x12b\n" +
	"\x11GetInvoiceDetails\x12%.finfocus.v1.GetInvoiceDetailsRequest\x1a&.finfocus.v1.GetInvoiceDetailsResponseB\xaf\x01\n" +
	"\x0fcom.finfocus.v1B\x11SupplementalProtoP\x01Z<github.com/rshade/finfocus-spec/sdk/go/proto/finfocus/v1;pbc\xa2\x02\x03FXX\xaa\x02\vFinfocus.V1\xca\x02\vFinfocus\\V1\xe2\x02\x17Finfocus\\V1\\GPBMetadata\xea\x02\fFinfocus::V1b\x06proto3"

var (
	file_finfocus_v1_supplemental_proto_rawDescOnce sync.Once
	file_finfocus_v1_supplemental_proto_rawDescData []byte
)

func file_finfocus_v1_supplemental_proto_rawDescGZIP() []byte {
	file_finfocus_v1_supplemental_proto_rawDescOnce.Do(func() {
		file_finfocus_v1_supplemental_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_finfocus_v1_supplemental_proto_rawDesc), len(file_finfocus_v1_supplemental_proto_rawDesc)))
	})
	return file_finfocus_v1_supplemental_proto_rawDescData
}

var file_finfocus_v1_supplemental_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_finfocus_v1_supplemental_proto_goTypes = []any{
	(*GetContractCommitmentsRequest)(nil),  // 0: finfocus.v1.GetContractCommitmentsRequest
	(*GetContractCommitmentsResponse)(nil), // 1: finfocus.v1.GetContractCommitmentsResponse
	(*GetBillingPeriodsRequest)(nil),       // 2: finfocus.v1.GetBillingPeriodsRequest
	(*GetBillingPeriodsResponse)(nil),      // 3: finfocus.v1.GetBillingPeriodsResponse
	(*GetInvoiceDetailsRequest)(nil),       // 4: finfocus.v1.GetInvoiceDetailsRequest
	(*GetInvoiceDetailsResponse)(nil),      // 5: finfocus.v1.GetInvoiceDetailsResponse
	(*timestamppb.Timestamp)(nil),          // 6: google.protobuf.Timestamp
	(*ContractCommitment)(nil),             // 7: finfocus.v1.ContractCommitment
	(*BillingPeriod)(nil),                  // 8: finfocus.v1.BillingPeriod
	(*InvoiceDetail)(nil),                  // 9: finfocus.v1.InvoiceDetail
}
var file_finfocus_v1_supplemental_proto_depIdxs = []int32{
	6,  // 0: finfocus.v1.GetContractCommitmentsRequest.start:type_name -> google.protobuf.Timestamp
	6,  // 1: finfocus.v1.GetContractCommitmentsRequest.end:type_name -> google.protobuf.Timestamp
	7,  // 2: finfocus.v1.GetContractCommitmentsResponse.commitments:type_name -> finfocus.v1.ContractCommitment
	6,  // 3: finfocus.v1.GetBillingPeriodsRequest.start:type_name -> google.protobuf.Timestamp
	6,  // 4: finfocus.v1.GetBillingPeriodsRequest.end:type_name -> google.protobuf.Timestamp
	8,  // 5: finfocus.v1.GetBillingPeriodsResponse.billing_periods:type_name -> finfocus.v1.BillingPeriod
	6,  // 6: finfocus.v1.GetInvoiceDetailsRequest.start:type_name -> google.protobuf.Timestamp
	6,  // 7: finfocus.v1.GetInvoiceDetailsRequest.end:type_name -> google.protobuf.Timestamp
	9,  // 8: finfocus.v1.GetInvoiceDetailsResponse.invoice_details:type_name -> finfocus.v1.InvoiceDetail
	0,  // 9: finfocus.v1.SupplementalDatasetService.GetContractCommitments:input_type -> finfocus.v1.GetContractCommitmentsRequest
	2,  // 10: finfocus.v1.SupplementalDatasetService.GetBillingPeriods:input_type -> finfocus.v1.GetBillingPeriodsRequest
	4,  // 11: finfocus.v1.SupplementalDatasetService.GetInvoiceDetails:input_type -> finfocus.v1.GetInvoiceDetailsRequest
	1,  // 12: finfocus.v1.SupplementalDatasetService.GetContractCommitments:output_type -> finfocus.v1.GetContractCommitmentsResponse
	3,  // 13: finfocus.v1.SupplementalDatasetService.GetBillingPeriods:output_type -> finfocus.v1.GetBillingPeriodsResponse
	5,  // 14: finfocus.v1.SupplementalDatasetService.GetInvoiceDetails:output_type -> finfocus.v1.GetInvoiceDetailsResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_finfocus_v1_supplemental_proto_init() }
func file_finfocus_v1_supplemental_proto_init() {
	if File_finfocus_v1_supplemental_proto != nil {
		return
	}
	file_finfocus_v1_focus_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_finfocus_v1_supplemental_proto_rawDesc), len(file_finfocus_v1_supplemental_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_finfocus_v1_supplemental_proto_goTypes,
		DependencyIndexes: file_finfocus_v1_supplemental_proto_depIdxs,
		MessageInfos:      file_finfocus_v1_supplemental_proto_msgTypes,
	}.Build()
	File_finfocus_v1_supplemental_proto = out.File
	file_finfocus_v1_supplemental_proto_goTypes = nil
	file_finfocus_v1_supplemental_proto_depIdxs = nil
}
