// Copyright 2026 The FinFocus Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: finfocus/v1/usage.proto

package pbc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StatsMode states how UsageRow amounts are to be interpreted.
type StatsMode int32

const (
	// Invalid in responses; amounts cannot be interpreted.
	StatsMode_STATS_MODE_UNSPECIFIED StatsMode = 0
	// Point-in-time per-hour rates (units "core", "GiB").
	StatsMode_STATS_MODE_RUN_RATE StatsMode = 1
	// Integrated over [start, end] (units "core-hours", "GiB-hours"). Applies
	// to every row, including node allocatable rows.
	StatsMode_STATS_MODE_HISTORICAL StatsMode = 2
)

// Enum value maps for StatsMode.
var (
	StatsMode_name = map[int32]string{
		0: "STATS_MODE_UNSPECIFIED",
		1: "STATS_MODE_RUN_RATE",
		2: "STATS_MODE_HISTORICAL",
	}
	StatsMode_value = map[string]int32{
		"STATS_MODE_UNSPECIFIED": 0,
		"STATS_MODE_RUN_RATE":    1,
		"STATS_MODE_HISTORICAL":  2,
	}
)

func (x StatsMode) Enum() *StatsMode {
	p := new(StatsMode)
	*p = x
	return p
}

func (x StatsMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatsMode) Descriptor() protoreflect.EnumDescriptor {
	return file_finfocus_v1_usage_proto_enumTypes[0].Descriptor()
}

func (StatsMode) Type() protoreflect.EnumType {
	return &file_finfocus_v1_usage_proto_enumTypes[0]
}

func (x StatsMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatsMode.Descriptor instead.
func (StatsMode) EnumDescriptor() ([]byte, []int) {
	return file_finfocus_v1_usage_proto_rawDescGZIP(), []int{0}
}

// GetStatsRequest selects the scope, window, workloads, and metrics to report.
type GetStatsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source-defined scope, such as a cluster identifier or kubeconfig context.
	// Empty means the source's default scope.
	Scope string `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	// Start of the historical window. Leave both start and end unset for
	// run-rate; setting exactly one is INVALID_ARGUMENT.
	Start *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	// End of the historical window. Must not be before start.
	End *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	// Workload filter; all entries must match. "namespace" is a reserved key
	// restricting workloads to that namespace; every other key is an exact-match
	// label filter. A label literally named "namespace" cannot be selected.
	Selector map[string]string `protobuf:"bytes,4,rep,name=selector,proto3" json:"selector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Metric names to return. Empty means the source's defaults. Unknown names
	// are ignored and reported in GetStatsResponse.warnings.
	Metrics       []string `protobuf:"bytes,5,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_finfocus_v1_usage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finfocus_v1_usage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_finfocus_v1_usage_proto_rawDescGZIP(), []int{0}
}

func (x *GetStatsRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *GetStatsRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *GetStatsRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *GetStatsRequest) GetSelector() map[string]string {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *GetStatsRequest) GetMetrics() []string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// GetStatsResponse carries usage rows, the resources that can be priced, and
// the mode actually served.
type GetStatsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Usage rows. A (subject, metric) pair appears at most once; sources
	// aggregate per-container data before responding.
	Rows []*UsageRow `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	// Priceable resources in the form hosts already price through cost-source
	// plugins. Nodes carry tags.kind="node", id equal to the node's "node"
	// subject value, tags.provider_id, and tags.capacity_type ("spot" or
	// "on-demand"). A control plane carries tags.kind="cluster". Every entry
	// has a non-empty id. Nodes that cannot be priced (for example Fargate or
	// an unknown provider) report capacity rows without a priceable entry.
	Priceable []*ResourceDescriptor `protobuf:"bytes,2,rep,name=priceable,proto3" json:"priceable,omitempty"`
	// Mode actually served; never STATS_MODE_UNSPECIFIED.
	Mode StatsMode `protobuf:"varint,3,opt,name=mode,proto3,enum=finfocus.v1.StatsMode" json:"mode,omitempty"`
	// Human-readable, non-fatal warnings (for example an unknown metric).
	Warnings      []string `protobuf:"bytes,4,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_finfocus_v1_usage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finfocus_v1_usage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_finfocus_v1_usage_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatsResponse) GetRows() []*UsageRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *GetStatsResponse) GetPriceable() []*ResourceDescriptor {
	if x != nil {
		return x.Priceable
	}
	return nil
}

func (x *GetStatsResponse) GetMode() StatsMode {
	if x != nil {
		return x.Mode
	}
	return StatsMode_STATS_MODE_UNSPECIFIED
}

func (x *GetStatsResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

// UsageRow is one measurement for one subject.
type UsageRow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifies what the usage belongs to. Keys: "cluster", "namespace",
	// "controller_kind", "controller", "pod", "node", "label.<key>", and the
	// required "kind", which is "workload" or "node".
	Subject map[string]string `protobuf:"bytes,1,rep,name=subject,proto3" json:"subject,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Metric name. Workload rows: "cpu_request", "mem_request", "cpu_usage",
	// "mem_usage". Node rows: "cpu_allocatable", "mem_allocatable".
	Metric string `protobuf:"bytes,2,opt,name=metric,proto3" json:"metric,omitempty"`
	// Non-negative, finite amount: a per-hour rate in STATS_MODE_RUN_RATE, or
	// integrated resource-hours in STATS_MODE_HISTORICAL.
	Amount float64 `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	// Unit: "core" or "GiB" for run-rate; "core-hours" or "GiB-hours" for
	// historical.
	Unit          string `protobuf:"bytes,4,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageRow) Reset() {
	*x = UsageRow{}
	mi := &file_finfocus_v1_usage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageRow) ProtoMessage() {}

func (x *UsageRow) ProtoReflect() protoreflect.Message {
	mi := &file_finfocus_v1_usage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageRow.ProtoReflect.Descriptor instead.
func (*UsageRow) Descriptor() ([]byte, []int) {
	return file_finfocus_v1_usage_proto_rawDescGZIP(), []int{2}
}

func (x *UsageRow) GetSubject() map[string]string {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *UsageRow) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *UsageRow) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UsageRow) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

var File_finfocus_v1_usage_proto protoreflect.FileDescriptor

const file_finfocus_v1_usage_proto_rawDesc = "" +
	"\n" +
	"\x17finfocus/v1/usage.proto\x12\vfinfocus.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cfinfocus/v1/costsource.proto\"\xa6\x02\n" +
	"\x0fGetStatsRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x120\n" +
	"\x05start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\x12F\n" +
	"\bselector\x18\x04 \x03(\v2*.finfocus.v1.GetStatsRequest.SelectorEntryR\bselector\x12\x18\n" +
	"\ametrics\x18\x05 \x03(\tR\ametrics\x1a;\n" +
	"\rSelectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc4\x01\n" +
	"\x10GetStatsResponse\x12)\n" +
	"\x04rows\x18\x01 \x03(\v2\x15.finfocus.v1.UsageRowR\x04rows\x12=\n" +
	"\tpriceable\x18\x02 \x03(\v2\x1f.finfocus.v1.ResourceDescriptorR\tpriceable\x12*\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x16.finfocus.v1.StatsModeR\x04mode\x12\x1a\n" +
	"\bwarnings\x18\x04 \x03(\tR\bwarnings\"\xc8\x01\n" +
	"\bUsageRow\x12<\n" +
	"\asubject\x18\x01 \x03(\v2\".finfocus.v1.UsageRow.SubjectEntryR\asubject\x12\x16\n" +
	"\x06metric\x18\x02 \x01(\tR\x06metric\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x12\n" +
	"\x04unit\x18\x04 \x01(\tR\x04unit\x1a:\n" +
	"\fSubjectEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*[\n" +
	"\tStatsMode\x12\x1a\n" +
	"\x16STATS_MODE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13STATS_MODE_RUN_RATE\x10\x01\x12\x19\n" +
	"\x15STATS_MODE_HISTORICAL\x10\x022]\n" +
	"\x12UsageSourceService\x12G\n" +
	"\bGetStats\x12\x1c.finfocus.v1.GetStatsRequest\x1a\x1d.finfocus.v1.GetStatsResponseB\xa8\x01\n" +
	"\x0fcom.finfocus.v1B\n" +
	"UsageProtoP\x01Z<github.com/rshade/finfocus-spec/sdk/go/proto/finfocus/v1;pbc\xa2\x02\x03FXX\xaa\x02\vFinfocus.V1\xca\x02\vFinfocus\\V1\xe2\x02\x17Finfocus\\V1\\GPBMetadata\xea\x02\fFinfocus::V1b\x06proto3"

var (
	file_finfocus_v1_usage_proto_rawDescOnce sync.Once
	file_finfocus_v1_usage_proto_rawDescData []byte
)

func file_finfocus_v1_usage_proto_rawDescGZIP() []byte {
	file_finfocus_v1_usage_proto_rawDescOnce.Do(func() {
		file_finfocus_v1_usage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_finfocus_v1_usage_proto_rawDesc), len(file_finfocus_v1_usage_proto_rawDesc)))
	})
	return file_finfocus_v1_usage_proto_rawDescData
}

var file_finfocus_v1_usage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_finfocus_v1_usage_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_finfocus_v1_usage_proto_goTypes = []any{
	(StatsMode)(0),                // 0: finfocus.v1.StatsMode
	(*GetStatsRequest)(nil),       // 1: finfocus.v1.GetStatsRequest
	(*GetStatsResponse)(nil),      // 2: finfocus.v1.GetStatsResponse
	(*UsageRow)(nil),              // 3: finfocus.v1.UsageRow
	nil,                           // 4: finfocus.v1.GetStatsRequest.SelectorEntry
	nil,                           // 5: finfocus.v1.UsageRow.SubjectEntry
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*ResourceDescriptor)(nil),    // 7: finfocus.v1.ResourceDescriptor
}
var file_finfocus_v1_usage_proto_depIdxs = []int32{
	6, // 0: finfocus.v1.GetStatsRequest.start:type_name -> google.protobuf.Timestamp
	6, // 1: finfocus.v1.GetStatsRequest.end:type_name -> google.protobuf.Timestamp
	4, // 2: finfocus.v1.GetStatsRequest.selector:type_name -> finfocus.v1.GetStatsRequest.SelectorEntry
	3, // 3: finfocus.v1.GetStatsResponse.rows:type_name -> finfocus.v1.UsageRow
	7, // 4: finfocus.v1.GetStatsResponse.priceable:type_name -> finfocus.v1.ResourceDescriptor
	0, // 5: finfocus.v1.GetStatsResponse.mode:type_name -> finfocus.v1.StatsMode
	5, // 6: finfocus.v1.UsageRow.subject:type_name -> finfocus.v1.UsageRow.SubjectEntry
	1, // 7: finfocus.v1.UsageSourceService.GetStats:input_type -> finfocus.v1.GetStatsRequest
	2, // 8: finfocus.v1.UsageSourceService.GetStats:output_type -> finfocus.v1.GetStatsResponse
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_finfocus_v1_usage_proto_init() }
func file_finfocus_v1_usage_proto_init() {
	if File_finfocus_v1_usage_proto != nil {
		return
	}
	file_finfocus_v1_costsource_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_finfocus_v1_usage_proto_rawDesc), len(file_finfocus_v1_usage_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_finfocus_v1_usage_proto_goTypes,
		DependencyIndexes: file_finfocus_v1_usage_proto_depIdxs,
		EnumInfos:         file_finfocus_v1_usage_proto_enumTypes,
		MessageInfos:      file_finfocus_v1_usage_proto_msgTypes,
	}.Build()
	File_finfocus_v1_usage_proto = out.File
	file_finfocus_v1_usage_proto_goTypes = nil
	file_finfocus_v1_usage_proto_depIdxs = nil
}
