// Copyright 2026 The FinFocus Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: finfocus/v1/usage.proto

package pbc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UsageSourceService_GetStats_FullMethodName = "/finfocus.v1.UsageSourceService/GetStats"
)

// UsageSourceServiceClient is the client API for UsageSourceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// UsageSourceService is implemented by usage-source plugins, which report how
// much CPU and memory workloads request or consume, backed by the Kubernetes
// API, Prometheus, Datadog, or similar systems. Usage sources carry no prices;
// hosts price the returned priceable resources through CostSourceService
// plugins and join them with usage rows on the node name.
//
// Error semantics:
//   - INVALID_ARGUMENT: only one of start/end is set, start is after end, or
//     the source cannot serve the requested mode (for example a run-rate-only
//     source asked for a historical window).
//   - PERMISSION_DENIED: credentials lack a required permission; the message
//     names the missing verb and resource (for example "cannot list pods").
//   - UNAUTHENTICATED: no usable credentials.
type UsageSourceServiceClient interface {
	// GetStats returns pre-integrated usage for workloads and nodes, and the
	// priceable resources (nodes, control plane) that usage runs on.
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error)
}

type usageSourceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUsageSourceServiceClient(cc grpc.ClientConnInterface) UsageSourceServiceClient {
	return &usageSourceServiceClient{cc}
}

func (c *usageSourceServiceClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, UsageSourceService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsageSourceServiceServer is the server API for UsageSourceService service.
// All implementations must embed UnimplementedUsageSourceServiceServer
// for forward compatibility.
//
// UsageSourceService is implemented by usage-source plugins, which report how
// much CPU and memory workloads request or consume, backed by the Kubernetes
// API, Prometheus, Datadog, or similar systems. Usage sources carry no prices;
// hosts price the returned priceable resources through CostSourceService
// plugins and join them with usage rows on the node name.
//
// Error semantics:
//   - INVALID_ARGUMENT: only one of start/end is set, start is after end, or
//     the source cannot serve the requested mode (for example a run-rate-only
//     source asked for a historical window).
//   - PERMISSION_DENIED: credentials lack a required permission; the message
//     names the missing verb and resource (for example "cannot list pods").
//   - UNAUTHENTICATED: no usable credentials.
type UsageSourceServiceServer interface {
	// GetStats returns pre-integrated usage for workloads and nodes, and the
	// priceable resources (nodes, control plane) that usage runs on.
	GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error)
	mustEmbedUnimplementedUsageSourceServiceServer()
}

// UnimplementedUsageSourceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUsageSourceServiceServer struct{}

func (UnimplementedUsageSourceServiceServer) GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedUsageSourceServiceServer) mustEmbedUnimplementedUsageSourceServiceServer() {}
func (UnimplementedUsageSourceServiceServer) testEmbeddedByValue()                            {}

// UnsafeUsageSourceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsageSourceServiceServer will
// result in compilation errors.
type UnsafeUsageSourceServiceServer interface {
	mustEmbedUnimplementedUsageSourceServiceServer()
}

func RegisterUsageSourceServiceServer(s grpc.ServiceRegistrar, srv UsageSourceServiceServer) {
	// If the following call panics, it indicates UnimplementedUsageSourceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UsageSourceService_ServiceDesc, srv)
}

func _UsageSourceService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsageSourceServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsageSourceService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsageSourceServiceServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UsageSourceService_ServiceDesc is the grpc.ServiceDesc for UsageSourceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UsageSourceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "finfocus.v1.UsageSourceService",
	HandlerType: (*UsageSourceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStats",
			Handler:    _UsageSourceService_GetStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "finfocus/v1/usage.proto",
}
