// Copyright 2026 The FinFocus Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: finfocus/v1/allocation.proto

package pbcconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/rshade/finfocus-spec/sdk/go/proto/finfocus/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AllocatorServiceName is the fully-qualified name of the AllocatorService service.
	AllocatorServiceName = "finfocus.v1.AllocatorService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AllocatorServiceAllocateProcedure is the fully-qualified name of the AllocatorService's Allocate
	// RPC.
	AllocatorServiceAllocateProcedure = "/finfocus.v1.AllocatorService/Allocate"
)

// AllocatorServiceClient is a client for the finfocus.v1.AllocatorService service.
type AllocatorServiceClient interface {
	// Allocate divides the successfully priced resources across the workloads
	// in usage, reporting unclaimed capacity as idle rows and shared
	// infrastructure as cluster rows.
	Allocate(context.Context, *connect.Request[v1.AllocateRequest]) (*connect.Response[v1.AllocateResponse], error)
}

// NewAllocatorServiceClient constructs a client for the finfocus.v1.AllocatorService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAllocatorServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AllocatorServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	allocatorServiceMethods := v1.File_finfocus_v1_allocation_proto.Services().ByName("AllocatorService").Methods()
	return &allocatorServiceClient{
		allocate: connect.NewClient[v1.AllocateRequest, v1.AllocateResponse](
			httpClient,
			baseURL+AllocatorServiceAllocateProcedure,
			connect.WithSchema(allocatorServiceMethods.ByName("Allocate")),
			connect.WithClientOptions(opts...),
		),
	}
}

// allocatorServiceClient implements AllocatorServiceClient.
type allocatorServiceClient struct {
	allocate *connect.Client[v1.AllocateRequest, v1.AllocateResponse]
}

// Allocate calls finfocus.v1.AllocatorService.Allocate.
func (c *allocatorServiceClient) Allocate(ctx context.Context, req *connect.Request[v1.AllocateRequest]) (*connect.Response[v1.AllocateResponse], error) {
	return c.allocate.CallUnary(ctx, req)
}

// AllocatorServiceHandler is an implementation of the finfocus.v1.AllocatorService service.
type AllocatorServiceHandler interface {
	// Allocate divides the successfully priced resources across the workloads
	// in usage, reporting unclaimed capacity as idle rows and shared
	// infrastructure as cluster rows.
	Allocate(context.Context, *connect.Request[v1.AllocateRequest]) (*connect.Response[v1.AllocateResponse], error)
}

// NewAllocatorServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAllocatorServiceHandler(svc AllocatorServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	allocatorServiceMethods := v1.File_finfocus_v1_allocation_proto.Services().ByName("AllocatorService").Methods()
	allocatorServiceAllocateHandler := connect.NewUnaryHandler(
		AllocatorServiceAllocateProcedure,
		svc.Allocate,
		connect.WithSchema(allocatorServiceMethods.ByName("Allocate")),
		connect.WithHandlerOptions(opts...),
	)
	return "/finfocus.v1.AllocatorService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AllocatorServiceAllocateProcedure:
			allocatorServiceAllocateHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAllocatorServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAllocatorServiceHandler struct{}

func (UnimplementedAllocatorServiceHandler) Allocate(context.Context, *connect.Request[v1.AllocateRequest]) (*connect.Response[v1.AllocateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("finfocus.v1.AllocatorService.Allocate is not implemented"))
}
