// Copyright 2026 The FinFocus Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: finfocus/v1/scoring.proto

package pbcconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/rshade/finfocus-spec/sdk/go/proto/finfocus/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RecommendationScorerServiceName is the fully-qualified name of the RecommendationScorerService
	// service.
	RecommendationScorerServiceName = "finfocus.v1.RecommendationScorerService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RecommendationScorerServiceScoreRecommendationsProcedure is the fully-qualified name of the
	// RecommendationScorerService's ScoreRecommendations RPC.
	RecommendationScorerServiceScoreRecommendationsProcedure = "/finfocus.v1.RecommendationScorerService/ScoreRecommendations"
)

// RecommendationScorerServiceClient is a client for the finfocus.v1.RecommendationScorerService
// service.
type RecommendationScorerServiceClient interface {
	// ScoreRecommendations rates each recommendation in the request. Results are
	// index-aligned: results[i] answers recommendations[i]. One failing entry
	// never fails the batch.
	ScoreRecommendations(context.Context, *connect.Request[v1.ScoreRecommendationsRequest]) (*connect.Response[v1.ScoreRecommendationsResponse], error)
}

// NewRecommendationScorerServiceClient constructs a client for the
// finfocus.v1.RecommendationScorerService service. By default, it uses the Connect protocol with
// the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To use
// the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRecommendationScorerServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RecommendationScorerServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	recommendationScorerServiceMethods := v1.File_finfocus_v1_scoring_proto.Services().ByName("RecommendationScorerService").Methods()
	return &recommendationScorerServiceClient{
		scoreRecommendations: connect.NewClient[v1.ScoreRecommendationsRequest, v1.ScoreRecommendationsResponse](
			httpClient,
			baseURL+RecommendationScorerServiceScoreRecommendationsProcedure,
			connect.WithSchema(recommendationScorerServiceMethods.ByName("ScoreRecommendations")),
			connect.WithClientOptions(opts...),
		),
	}
}

// recommendationScorerServiceClient implements RecommendationScorerServiceClient.
type recommendationScorerServiceClient struct {
	scoreRecommendations *connect.Client[v1.ScoreRecommendationsRequest, v1.ScoreRecommendationsResponse]
}

// ScoreRecommendations calls finfocus.v1.RecommendationScorerService.ScoreRecommendations.
func (c *recommendationScorerServiceClient) ScoreRecommendations(ctx context.Context, req *connect.Request[v1.ScoreRecommendationsRequest]) (*connect.Response[v1.ScoreRecommendationsResponse], error) {
	return c.scoreRecommendations.CallUnary(ctx, req)
}

// RecommendationScorerServiceHandler is an implementation of the
// finfocus.v1.RecommendationScorerService service.
type RecommendationScorerServiceHandler interface {
	// ScoreRecommendations rates each recommendation in the request. Results are
	// index-aligned: results[i] answers recommendations[i]. One failing entry
	// never fails the batch.
	ScoreRecommendations(context.Context, *connect.Request[v1.ScoreRecommendationsRequest]) (*connect.Response[v1.ScoreRecommendationsResponse], error)
}

// NewRecommendationScorerServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRecommendationScorerServiceHandler(svc RecommendationScorerServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	recommendationScorerServiceMethods := v1.File_finfocus_v1_scoring_proto.Services().ByName("RecommendationScorerService").Methods()
	recommendationScorerServiceScoreRecommendationsHandler := connect.NewUnaryHandler(
		RecommendationScorerServiceScoreRecommendationsProcedure,
		svc.ScoreRecommendations,
		connect.WithSchema(recommendationScorerServiceMethods.ByName("ScoreRecommendations")),
		connect.WithHandlerOptions(opts...),
	)
	return "/finfocus.v1.RecommendationScorerService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RecommendationScorerServiceScoreRecommendationsProcedure:
			recommendationScorerServiceScoreRecommendationsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRecommendationScorerServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRecommendationScorerServiceHandler struct{}

func (UnimplementedRecommendationScorerServiceHandler) ScoreRecommendations(context.Context, *connect.Request[v1.ScoreRecommendationsRequest]) (*connect.Response[v1.ScoreRecommendationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("finfocus.v1.RecommendationScorerService.ScoreRecommendations is not implemented"))
}
