// Copyright 2026 The FinFocus Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: finfocus/v1/supplemental.proto

package pbcconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/rshade/finfocus-spec/sdk/go/proto/finfocus/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SupplementalDatasetServiceName is the fully-qualified name of the SupplementalDatasetService
	// service.
	SupplementalDatasetServiceName = "finfocus.v1.SupplementalDatasetService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SupplementalDatasetServiceGetContractCommitmentsProcedure is the fully-qualified name of the
	// SupplementalDatasetService's GetContractCommitments RPC.
	SupplementalDatasetServiceGetContractCommitmentsProcedure = "/finfocus.v1.SupplementalDatasetService/GetContractCommitments"
	// SupplementalDatasetServiceGetBillingPeriodsProcedure is the fully-qualified name of the
	// SupplementalDatasetService's GetBillingPeriods RPC.
	SupplementalDatasetServiceGetBillingPeriodsProcedure = "/finfocus.v1.SupplementalDatasetService/GetBillingPeriods"
	// SupplementalDatasetServiceGetInvoiceDetailsProcedure is the fully-qualified name of the
	// SupplementalDatasetService's GetInvoiceDetails RPC.
	SupplementalDatasetServiceGetInvoiceDetailsProcedure = "/finfocus.v1.SupplementalDatasetService/GetInvoiceDetails"
)

// SupplementalDatasetServiceClient is a client for the finfocus.v1.SupplementalDatasetService
// service.
type SupplementalDatasetServiceClient interface {
	// GetContractCommitments returns a page of FOCUS Contract Commitment records
	// whose period overlaps the requested window.
	GetContractCommitments(context.Context, *connect.Request[v1.GetContractCommitmentsRequest]) (*connect.Response[v1.GetContractCommitmentsResponse], error)
	// GetBillingPeriods returns a page of FOCUS Billing Period records whose
	// period overlaps the requested window.
	GetBillingPeriods(context.Context, *connect.Request[v1.GetBillingPeriodsRequest]) (*connect.Response[v1.GetBillingPeriodsResponse], error)
	// GetInvoiceDetails returns a page of FOCUS Invoice Detail records whose
	// billing period overlaps the requested window.
	GetInvoiceDetails(context.Context, *connect.Request[v1.GetInvoiceDetailsRequest]) (*connect.Response[v1.GetInvoiceDetailsResponse], error)
}

// NewSupplementalDatasetServiceClient constructs a client for the
// finfocus.v1.SupplementalDatasetService service. By default, it uses the Connect protocol with the
// binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To use the
// gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSupplementalDatasetServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SupplementalDatasetServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	supplementalDatasetServiceMethods := v1.File_finfocus_v1_supplemental_proto.Services().ByName("SupplementalDatasetService").Methods()
	return &supplementalDatasetServiceClient{
		getContractCommitments: connect.NewClient[v1.GetContractCommitmentsRequest, v1.GetContractCommitmentsResponse](
			httpClient,
			baseURL+SupplementalDatasetServiceGetContractCommitmentsProcedure,
			connect.WithSchema(supplementalDatasetServiceMethods.ByName("GetContractCommitments")),
			connect.WithClientOptions(opts...),
		),
		getBillingPeriods: connect.NewClient[v1.GetBillingPeriodsRequest, v1.GetBillingPeriodsResponse](
			httpClient,
			baseURL+SupplementalDatasetServiceGetBillingPeriodsProcedure,
			connect.WithSchema(supplementalDatasetServiceMethods.ByName("GetBillingPeriods")),
			connect.WithClientOptions(opts...),
		),
		getInvoiceDetails: connect.NewClient[v1.GetInvoiceDetailsRequest, v1.GetInvoiceDetailsResponse](
			httpClient,
			baseURL+SupplementalDatasetServiceGetInvoiceDetailsProcedure,
			connect.WithSchema(supplementalDatasetServiceMethods.ByName("GetInvoiceDetails")),
			connect.WithClientOptions(opts...),
		),
	}
}

// supplementalDatasetServiceClient implements SupplementalDatasetServiceClient.
type supplementalDatasetServiceClient struct {
	getContractCommitments *connect.Client[v1.GetContractCommitmentsRequest, v1.GetContractCommitmentsResponse]
	getBillingPeriods      *connect.Client[v1.GetBillingPeriodsRequest, v1.GetBillingPeriodsResponse]
	getInvoiceDetails      *connect.Client[v1.GetInvoiceDetailsRequest, v1.GetInvoiceDetailsResponse]
}

// GetContractCommitments calls finfocus.v1.SupplementalDatasetService.GetContractCommitments.
func (c *supplementalDatasetServiceClient) GetContractCommitments(ctx context.Context, req *connect.Request[v1.GetContractCommitmentsRequest]) (*connect.Response[v1.GetContractCommitmentsResponse], error) {
	return c.getContractCommitments.CallUnary(ctx, req)
}

// GetBillingPeriods calls finfocus.v1.SupplementalDatasetService.GetBillingPeriods.
func (c *supplementalDatasetServiceClient) GetBillingPeriods(ctx context.Context, req *connect.Request[v1.GetBillingPeriodsRequest]) (*connect.Response[v1.GetBillingPeriodsResponse], error) {
	return c.getBillingPeriods.CallUnary(ctx, req)
}

// GetInvoiceDetails calls finfocus.v1.SupplementalDatasetService.GetInvoiceDetails.
func (c *supplementalDatasetServiceClient) GetInvoiceDetails(ctx context.Context, req *connect.Request[v1.GetInvoiceDetailsRequest]) (*connect.Response[v1.GetInvoiceDetailsResponse], error) {
	return c.getInvoiceDetails.CallUnary(ctx, req)
}

// SupplementalDatasetServiceHandler is an implementation of the
// finfocus.v1.SupplementalDatasetService service.
type SupplementalDatasetServiceHandler interface {
	// GetContractCommitments returns a page of FOCUS Contract Commitment records
	// whose period overlaps the requested window.
	GetContractCommitments(context.Context, *connect.Request[v1.GetContractCommitmentsRequest]) (*connect.Response[v1.GetContractCommitmentsResponse], error)
	// GetBillingPeriods returns a page of FOCUS Billing Period records whose
	// period overlaps the requested window.
	GetBillingPeriods(context.Context, *connect.Request[v1.GetBillingPeriodsRequest]) (*connect.Response[v1.GetBillingPeriodsResponse], error)
	// GetInvoiceDetails returns a page of FOCUS Invoice Detail records whose
	// billing period overlaps the requested window.
	GetInvoiceDetails(context.Context, *connect.Request[v1.GetInvoiceDetailsRequest]) (*connect.Response[v1.GetInvoiceDetailsResponse], error)
}

// NewSupplementalDatasetServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSupplementalDatasetServiceHandler(svc SupplementalDatasetServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	supplementalDatasetServiceMethods := v1.File_finfocus_v1_supplemental_proto.Services().ByName("SupplementalDatasetService").Methods()
	supplementalDatasetServiceGetContractCommitmentsHandler := connect.NewUnaryHandler(
		SupplementalDatasetServiceGetContractCommitmentsProcedure,
		svc.GetContractCommitments,
		connect.WithSchema(supplementalDatasetServiceMethods.ByName("GetContractCommitments")),
		connect.WithHandlerOptions(opts...),
	)
	supplementalDatasetServiceGetBillingPeriodsHandler := connect.NewUnaryHandler(
		SupplementalDatasetServiceGetBillingPeriodsProcedure,
		svc.GetBillingPeriods,
		connect.WithSchema(supplementalDatasetServiceMethods.ByName("GetBillingPeriods")),
		connect.WithHandlerOptions(opts...),
	)
	supplementalDatasetServiceGetInvoiceDetailsHandler := connect.NewUnaryHandler(
		SupplementalDatasetServiceGetInvoiceDetailsProcedure,
		svc.GetInvoiceDetails,
		connect.WithSchema(supplementalDatasetServiceMethods.ByName("GetInvoiceDetails")),
		connect.WithHandlerOptions(opts...),
	)
	return "/finfocus.v1.SupplementalDatasetService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SupplementalDatasetServiceGetContractCommitmentsProcedure:
			supplementalDatasetServiceGetContractCommitmentsHandler.ServeHTTP(w, r)
		case SupplementalDatasetServiceGetBillingPeriodsProcedure:
			supplementalDatasetServiceGetBillingPeriodsHandler.ServeHTTP(w, r)
		case SupplementalDatasetServiceGetInvoiceDetailsProcedure:
			supplementalDatasetServiceGetInvoiceDetailsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSupplementalDatasetServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSupplementalDatasetServiceHandler struct{}

func (UnimplementedSupplementalDatasetServiceHandler) GetContractCommitments(context.Context, *connect.Request[v1.GetContractCommitmentsRequest]) (*connect.Response[v1.GetContractCommitmentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("finfocus.v1.SupplementalDatasetService.GetContractCommitments is not implemented"))
}

func (UnimplementedSupplementalDatasetServiceHandler) GetBillingPeriods(context.Context, *connect.Request[v1.GetBillingPeriodsRequest]) (*connect.Response[v1.GetBillingPeriodsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("finfocus.v1.SupplementalDatasetService.GetBillingPeriods is not implemented"))
}

func (UnimplementedSupplementalDatasetServiceHandler) GetInvoiceDetails(context.Context, *connect.Request[v1.GetInvoiceDetailsRequest]) (*connect.Response[v1.GetInvoiceDetailsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("finfocus.v1.SupplementalDatasetService.GetInvoiceDetails is not implemented"))
}
