// Copyright 2026 The FinFocus Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: finfocus/v1/usage.proto

package pbcconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/rshade/finfocus-spec/sdk/go/proto/finfocus/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// UsageSourceServiceName is the fully-qualified name of the UsageSourceService service.
	UsageSourceServiceName = "finfocus.v1.UsageSourceService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UsageSourceServiceGetStatsProcedure is the fully-qualified name of the UsageSourceService's
	// GetStats RPC.
	UsageSourceServiceGetStatsProcedure = "/finfocus.v1.UsageSourceService/GetStats"
)

// UsageSourceServiceClient is a client for the finfocus.v1.UsageSourceService service.
type UsageSourceServiceClient interface {
	// GetStats returns pre-integrated usage for workloads and nodes, and the
	// priceable resources (nodes, control plane) that usage runs on.
	GetStats(context.Context, *connect.Request[v1.GetStatsRequest]) (*connect.Response[v1.GetStatsResponse], error)
}

// NewUsageSourceServiceClient constructs a client for the finfocus.v1.UsageSourceService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUsageSourceServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UsageSourceServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	usageSourceServiceMethods := v1.File_finfocus_v1_usage_proto.Services().ByName("UsageSourceService").Methods()
	return &usageSourceServiceClient{
		getStats: connect.NewClient[v1.GetStatsRequest, v1.GetStatsResponse](
			httpClient,
			baseURL+UsageSourceServiceGetStatsProcedure,
			connect.WithSchema(usageSourceServiceMethods.ByName("GetStats")),
			connect.WithClientOptions(opts...),
		),
	}
}

// usageSourceServiceClient implements UsageSourceServiceClient.
type usageSourceServiceClient struct {
	getStats *connect.Client[v1.GetStatsRequest, v1.GetStatsResponse]
}

// GetStats calls finfocus.v1.UsageSourceService.GetStats.
func (c *usageSourceServiceClient) GetStats(ctx context.Context, req *connect.Request[v1.GetStatsRequest]) (*connect.Response[v1.GetStatsResponse], error) {
	return c.getStats.CallUnary(ctx, req)
}

// UsageSourceServiceHandler is an implementation of the finfocus.v1.UsageSourceService service.
type UsageSourceServiceHandler interface {
	// GetStats returns pre-integrated usage for workloads and nodes, and the
	// priceable resources (nodes, control plane) that usage runs on.
	GetStats(context.Context, *connect.Request[v1.GetStatsRequest]) (*connect.Response[v1.GetStatsResponse], error)
}

// NewUsageSourceServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUsageSourceServiceHandler(svc UsageSourceServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	usageSourceServiceMethods := v1.File_finfocus_v1_usage_proto.Services().ByName("UsageSourceService").Methods()
	usageSourceServiceGetStatsHandler := connect.NewUnaryHandler(
		UsageSourceServiceGetStatsProcedure,
		svc.GetStats,
		connect.WithSchema(usageSourceServiceMethods.ByName("GetStats")),
		connect.WithHandlerOptions(opts...),
	)
	return "/finfocus.v1.UsageSourceService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UsageSourceServiceGetStatsProcedure:
			usageSourceServiceGetStatsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUsageSourceServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedUsageSourceServiceHandler struct{}

func (UnimplementedUsageSourceServiceHandler) GetStats(context.Context, *connect.Request[v1.GetStatsRequest]) (*connect.Response[v1.GetStatsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("finfocus.v1.UsageSourceService.GetStats is not implemented"))
}
